espressif/esp-protocols

components/esp_modem/src/esp_modem_c_api.cpp
Implements sync() in the C API
=> Implement esp_modem_sync for the C API

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
Follow up from https://github.com/espressif/esp-idf/issues/8367 and https://github.com/espressif/esp-idf/pull/8395 :)
=> esp_websocket_client: Expose frame fin flag in websocket event

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
[Redo of espressif/esp-idf pull 8486](https://github.com/espressif/esp-idf/pull/8486)
=> Add methods to allow get/set of websocket client ping interval (IDFGH-7096)

components/esp_modem/include/generate/esp_modem_command_declare.inc
seems not to be the Module Name.
=> seems not to be the Module Name.  (IDFGH-7402)

components/esp_modem/include/generate/esp_modem_command_declare.inc, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/src/esp_modem_command_library.cpp
=> Add raw command (IDFGH-7658)

components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/include/generate/esp_modem_command_declare.inc, components/esp_modem/src/esp_modem_c_api.cpp
=> fix(esp-modem): Add missing set_pdp_context() to C-API

components/esp_modem/include/cxx_include/esp_modem_dce_module.hpp, components/esp_modem/include/generate/esp_modem_command_declare.inc, components/esp_modem/src/esp_modem_command_library.cpp, components/esp_modem/test/host_test/main/LoopbackTerm.cpp, components/esp_modem/test/host_test/main/test_modem.cpp
Closes https://github.com/espressif/esp-protocols/issues/80
=> feat(esp_modem): Add optional ACT to operator-name

components/asio/idf_component.yml, components/esp_websocket_client/idf_component.yml, components/mdns/idf_component.yml
Update components version afrer change d66f9dc15801c723d07e3dedd69b68e7e97e7a2e
=> Bump asio/mdns/esp_websocket_client versions

components/mdns/examples/CMakeLists.txt, components/mdns/mdns.c, components/mdns/private_include/mdns_private.h
Updated and rebased https://github.com/espressif/esp-protocols/pull/98 since it is a very important bugfix
=> mdns: fix bit order issue in DNS header flags (updated)

components/esp_modem/src/esp_modem_cmux.cpp
* Fix DISC message's control field (0xFF->0xFE) to keep Poll bit cleared
* Accept UIH resp on DISC for both (0xFF, 0xFE) ignoring P/F bit
* Fix timeout processing when handling DISC message
Closes https://github.com/espressif/esp-protocols/issues/103
=> fix(esp_modem): Correct exit of CMUX mode

components/esp_modem/examples/ap_to_pppos/main/ap_to_pppos.c, components/esp_modem/idf_component.yml, components/esp_modem/private_include/uart_compat.h, components/esp_modem/src/esp_modem_netif.cpp
Fix IDF version resolution in esp_modem
=> esp_modem: Fix IDF version resolution (IDFGH-8271)

components/esp_modem/examples/modem_console/main/Kconfig.projbuild
remove unused Config Parameters !
=> remove unused Config Parameters ! (IDFGH-8442)

components/esp_modem/examples/modem_psm/CMakeLists.txt, components/esp_modem/examples/modem_psm/README.md, components/esp_modem/examples/modem_psm/main/CMakeLists.txt, components/esp_modem/examples/modem_psm/main/Kconfig.projbuild, components/esp_modem/examples/modem_psm/main/modem_psm.c, components/esp_modem/examples/modem_psm/sdkconfig.defaults
Added example demonstrating Power Saving Mode(PSM) in Sim70XX modems along with Deep sleep and Light Sleep modes in esp32.
=> esp_modem/examples: Added example Power Saving Mode(PSM) in LTE modem.

components/mdns/mdns.c
- Array compared against 0, code with NO_EFFECT
- dereference null pointer, FORWARD_NULL check
=> mdns: fix some coverity reported issues

components/asio/README.md, components/esp_modem/README.md, components/esp_websocket_client/README.md, components/mdns/README.md
Added badges with versions in README files to following components:
- asio
- eso_modem
- esp_websocket_client
- mdns
=> Added badges with version of components to the respective README files (IDFGH-8940)

components/esp_modem/src/esp_modem_command_library.cpp
AT+IFC=2,2 instead AT+IFC=2, 2
=> Update esp_modem_command_library.cpp (IDFGH-9018)

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/examples/main/websocket_example.c, components/esp_websocket_client/examples/pytest_websocket.py, components/mdns/mdns.c, components/mdns/mdns_networking_lwip.c, components/mdns/mdns_networking_socket.c, components/mdns/tests/test_apps/main/main.c, components/mdns/tests/test_apps/main/mdns_test.c
Made the logging tags lower case.
=> Unite all tags under common structure (IDFGH-9399)

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/examples/main/websocket_example.c, components/esp_websocket_client/include/esp_websocket_client.h
Based on https://github.com/espressif/esp-protocols/pull/151
=> esp_websocket_client: Improve error handling (IDFGH-8444)

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/other-issue.yml
Adding issue templates into repository. Please check the templates and let me know if the provided documentation, description, requested data or whole templates make sense.
=> Add issue templates

.github/workflows/target-test.yml, components/esp_websocket_client/idf_component.yml
Updated tests to run agains release-v5.0
=> websocket: Updated version to 1.0.0

components/esp_mqtt_cxx/esp_mqtt_cxx.cpp
Configuration for client authentication methods certificate/key and secure element added.
=> MQTT: complete client authentication configuration (IDFGH-9656)

components/mdns/examples/main/mdns_example_main.c, components/mdns/include/mdns.h, components/mdns/mdns.c
We need APIs which can search the delegated services.
=> mdns: Add APIs to lookup delegated services (IDFGH-9790)

.github/workflows/publish-docs-component.yml
* build all components
* deploys all component's latest docs
* if version of a component changed -> deploys this component docs as the specific version ref
=> ci(common): Fix build and deploy docs jobs

.github/workflows/websocket__build-target-test.yml
* Adds v5.1 to the list of IDF releases for builds/tests
* Cleanup + prepare for more tests
=> websocket(ci): Add IDF v5.1 in IDF tests for websockets

components/mdns/examples/main/mdns_example_main.c, components/mdns/include/mdns.h, components/mdns/mdns.c
We need the APIs to lookup self hosted services and get the self hostname.
=> mdns: Add APIs for looking up self hosted services and getting the self hostname (IDFGH-10130)

components/mdns/mdns.c
According to [RFC6763-section12.1](https://www.rfc-editor.org/rfc/rfc6763#section-12.1), for DNS-SD, SRV, TXT and all address records should be included in additional records.
This PR will add the related records, only for delegated scenario, in to additional records.
=> fix(mdns): Fix delegated service PTR response (IDFGH-10237)

.github/workflows/modem__target-test.yml, components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml, docs/esp_modem/en/README.rst
Also updates self-hosted runner tag (from runner name to test scope related tag)
=> docs(modem): Add known issues section to docs

components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/idf_component.yml
1.1.0
Features
- Added linux port for websocket (a22391a) 
Bug Fixes
- added idf_component.yml for examples (d273e10)
=> bump(websocket): 1.0.1 -> 1.1.0

.github/workflows/publish-docs-component.yml, README.md, components/console_simple_init/.cz.yaml, components/console_simple_init/CHANGELOG.md, components/console_simple_init/examples/console_basic/main/console_basic.c, components/console_simple_init/idf_component.yml
Fixed bump version check in publish-docs-component.yml
=> fix(console): Fixed bump version check in publish-docs yml

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/examples/linux/main/main.c, components/esp_websocket_client/include/esp_websocket_client.h
Added new API esp_websocket_client_append_header
Also updated host example, to enhance covertly analyzing
=> feat(websocket): Added new API `esp_websocket_client_append_header` (IDF-7893)

components/esp_websocket_client/esp_websocket_client.c
Origin https://github.com/espressif/esp-protocols/pull/393
=> fix(websocket): Return status code correctly on esp_websocket_client (IDFGH-11290)

components/asio/examples/async_request/README.md, docs/asio/en/index.rst
- Removes mention to WolfSSL
- Fix links to examples
- Fix diagram markdwon.
=> Updates asio docs

.github/workflows/console_cmd_ping__build.yml, .github/workflows/publish-docs-component.yml, README.md, components/console_cmd_ping/.cz.yaml, components/console_cmd_ping/CMakeLists.txt, components/console_cmd_ping/LICENSE, components/console_cmd_ping/README.md, components/console_cmd_ping/console_ping.c, components/console_cmd_ping/console_ping.h, components/console_cmd_ping/examples/ping-basic/CMakeLists.txt, components/console_cmd_ping/examples/ping-basic/main/CMakeLists.txt, components/console_cmd_ping/examples/ping-basic/main/idf_component.yml, components/console_cmd_ping/examples/ping-basic/main/ping-basic.c, components/console_cmd_ping/examples/ping-basic/pytest_ping_basic.py, components/console_cmd_ping/idf_component.yml
The component provides a console where the 'ping' command can be executed.
=> feat(console): Added ping command to console component

components/console_cmd_ping/.cz.yaml, components/console_cmd_ping/CHANGELOG.md, components/console_cmd_ping/idf_component.yml
1.0.0
Features
- Added ping command to console component (7babdeb9)
=> bump(console): First version [1.0.0]

components/esp_modem/include/cxx_include/esp_modem_command_library.hpp, components/esp_modem/include/cxx_include/esp_modem_dce_module.hpp, components/esp_modem/src/esp_modem_command_library.cpp, components/esp_modem/src/esp_modem_modules.cpp
Closes https://github.com/espressif/esp-protocols/issues/455
=> fix(modem): Fixed set_pdp_context() command timeout

README.md, components/console_cmd_wifi/.cz.yaml, components/console_cmd_wifi/CHANGELOG.md, components/console_cmd_wifi/LICENSE, components/console_cmd_wifi/idf_component.yml
Added License file to console_cmd_wifi component.
=> fix(console): Fixed license file for console_cmd_wifi

components/mdns/mdns.c
fix loop problem in function '_copy_delegated_host_address_list'
=> fix(mdns): fix copy delegated host addr (IDFGH-11829)

.github/workflows/console_cmd_iperf__build.yml, .github/workflows/publish-docs-component.yml, components/console_cmd_iperf/.cz.yaml, components/console_cmd_iperf/CHANGELOG.md, components/console_cmd_iperf/CMakeLists.txt, components/console_cmd_iperf/LICENSE, components/console_cmd_iperf/README.md, components/console_cmd_iperf/console_iperf.c, components/console_cmd_iperf/console_iperf.h, components/console_cmd_iperf/examples/iperf-basic/CMakeLists.txt, components/console_cmd_iperf/examples/iperf-basic/main/CMakeLists.txt, components/console_cmd_iperf/examples/iperf-basic/main/idf_component.yml, components/console_cmd_iperf/examples/iperf-basic/main/iperf-basic.c, components/console_cmd_iperf/examples/iperf-basic/pytest_iperf-basic.py, components/console_cmd_iperf/idf_component.yml
The component provides a console where the 'iperf' command can be executed for any example project.
=> feat(console): Added component with iperf command

components/esp_mqtt_cxx/README.md
Link in the component README was incorrect.
=> Incorrect documentation link

components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/test/README.md, components/esp_modem/test/target_ota/components/manual_ota/manual_ota.cpp, components/esp_modem/test/target_ota/components/manual_ota/manual_ota.hpp
Closes https://github.com/espressif/esp-protocols/issues/485
=> fix(modem): Added C-API to configure APN

components/eppp_link/include/eppp_link.h
Fixes initialization issues from C++
=> fix(eppp): Fixed default config designated init issue in C++

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.3.1
Bug Fixes
- free txt value len (afd98bb)
=> bump(mdns): 1.3.0 -> 1.3.1

components/esp_wifi_remote/.cz.yaml, components/esp_wifi_remote/CHANGELOG.md, components/esp_wifi_remote/idf_component.yml
- add esp_wifi_internal_tx_by_ref (ba35d14e)
- Make wifi_remote depend on esp_hosted (ac9972aa)
=> bump(wifi_remote): 0.2.3 -> 0.3.0

components/mdns/mdns.c
When browsing, it is necessary to check for new TXT records. If the TXT records are changed, an update operation should be performed.
=> feat(mdns): check if the txt items is changed when browsing

components/sock_utils/CMakeLists.txt, components/sock_utils/README.md, components/sock_utils/include/gethostname.h, components/sock_utils/src/gethostname.c, components/sock_utils/test/host/main/test_sock_utils.cpp
* to address https://github.com/espressif/esp-idf/issues/14849
=> [sock-utils]: Add support for gethostname()

.github/workflows/modem__target-test.yml
fixes https://github.com/espressif/esp-protocols/actions/runs/12931410602/job/36065204630
=> [modem]: Fix deprecated CI download action

.pre-commit-config.yaml, common_components/linux_compat/freertos/freertos_linux.c, common_components/linux_compat/freertos/include/freertos/task.h, components/mdns/mdns.c, components/mdns/tests/test_afl_fuzz_host/esp32_mock.c, components/mdns/tests/test_afl_fuzz_host/esp32_mock.h
* we may need to fix some freertos/linux compat files, I think they were formatted incorrectly
=> [ci]: Fix pre-commit hook to call astyle correctly

common_components/linux_compat/freertos/freertos_linux.c, components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml, components/mdns/mdns.c
Need to wait for the task to be deleted before destroy its stack
=> [mdns]: Fix potential task delete race

components/esp_modem/src/esp_modem_cmux.cpp
Accepting https://github.com/espressif/esp-protocols/pull/782
=> [modem]: Fix cmux log message

components/esp_modem/src/esp_modem_command_library.cpp
Closes https://github.com/espressif/esp-protocols/issues/826
---
The `get_network_registration_state()` function failed on SIM7000 modems because it expected `AT+CEREG` responses with multiple parameters (2+ commas), but SIM7000 returns only 2 parameters with 1 comma: `+CEREG: 0,5`.
Improved the parsing logic to:
First look for \r or \n as end delimiters (handles SIM7000 case)
Fall back to second comma if no line endings found (maintains backward compatibility)
Use end of string as final fallback
Fixed boundary condition by removing the problematic -1 offset
The fix maintains full compatibility with modems that return multiple parameters (like +CEREG: 0,1,2,3,4,5) while correctly handling the SIM7000 format (+CEREG: 0,5).
=> [modem]: Fix get_network_registration_state() to accept two params

.github/workflows/mosq__build.yml, components/mosquitto/.cz.yaml, components/mosquitto/CHANGELOG.md, components/mosquitto/Kconfig, components/mosquitto/api.md, components/mosquitto/examples/serverless_mqtt/main/wifi_connect.c, components/mosquitto/idf_component.yml, components/mosquitto/port/include/mosq_broker.h, components/mosquitto/port/net__esp_tls.c, components/mosquitto/port/priv_include/config.h
- Support build on older IDF branches ([b0e3397e](https://github.com/espressif/esp-protocols/commit/b0e3397e))
- Fix misleading error when accepting connection ([27055fdc](https://github.com/espressif/esp-protocols/commit/27055fdc), [#807](https://github.com/espressif/esp-protocols/issues/807))
- Make mosquitto component c++ compatible ([c4169765](https://github.com/espressif/esp-protocols/commit/c4169765), [#817](https://github.com/espressif/esp-protocols/issues/817))
- include config.h before any system header ([1b1ede43](https://github.com/espressif/esp-protocols/commit/1b1ede43))
* https://github.com/espressif/esp-protocols/issues/807
* https://github.com/espressif/esp-protocols/issues/817
* https://github.com/espressif/esp-protocols/issues/816
* …
=> [mosq]: Fix some recent bugs

components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/idf_component.yml
1.5.0
Features
- add separate tx lock for send and receive (250eebf)
- add unregister event to websocket client (ce16050)
- add ability to reconnect after close (19891d8) Bug Fixes
- release client-lock during WEBSOCKET_EVENT_DATA (030cb75)
---
=> bump(websocket): 1.4.0 -> 1.5.0
