espressif/esp-protocols

components/esp_modem/include/cxx_include/esp_modem_primitives.hpp
This commit updates the default handles for Task type and Signal Group
type to match the struct type handle from freertos v10.4.3.
Signed-off-by: Sudeep Mohanty <sudeep.mohanty@espressif.com>
=> esp_modem: Update Task handle and Event Group handle to match freertos v10.4.3

.github/workflows/sync_issues.yml, .github/workflows/upload_component.yml
This PR defines two new actions:
* Uploads component `esp_modem` components to Espressif component registry
* Synchronizes issues/issue-comments to internal JIRA project (component=`esp-protocols`)
=> Added actions to upload components and sync issues

README.md, components/esp_modem/README.md, components/esp_modem/docs/api_docs.rst, components/esp_modem/idf_component.yml, components/esp_modem/include/cxx_include/esp_modem_dce_module.hpp, components/esp_modem/include/cxx_include/esp_modem_primitives.hpp, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/src/esp_modem_primitives_freertos.cpp
Adds missing C-only API so this component could be used for smooth migration of  https://github.com/espressif/esp-idf/tree/master/examples/protocols/pppos_client.
esp-modem was tested mainly with C++ applications and a very simple plain C demo project, which didn't read all the numbers and details using AT commands.
Also updated links to the generated docs on GitHub pages and increased version number (`0.1.9` -> `0.1.11`, because `0.1.10` was already published on WIP branches)
=> fix(esp_modem): Add missing C API

components/esp_modem/idf_component.yml, components/esp_modem/include/cxx_include/esp_modem_primitives.hpp
This commit includes freertos/event_groups.h header and removes the
forward declaration for EventGroupHandle_t.
Signed-off-by: Sudeep Mohanty <sudeep.mohanty@espressif.com>
=> esp_modem: Update FreeRTOS EventQueueHandle_t forward declaration

components/esp_modem/include/cxx_include/esp_modem_dce_module.hpp, components/esp_modem/src/esp_modem_modules.cpp, components/esp_modem/test/host_test/main/LoopbackTerm.cpp, components/esp_modem/test/host_test/main/test_modem.cpp
Module names were hard-coded strings defined as `override` method for different modules.
This fixes basic IDF test case which supplied dummy module name.
=> fix(esp_modem): Read module name with AT commands

components/esp_modem/idf_component.yml, components/esp_modem/src/esp_modem_command_library.cpp, components/esp_modem/test/host_test/main/LoopbackTerm.cpp, components/esp_modem/test/host_test/main/test_modem.cpp
Variable `pos`  was meant to hold position of first `,` (comma) appearance in the parsed string, but due to wrong parentheses it contained the boolean representation of not equal to `string::npos`
It wasn't caught by the tests, since the case used one-letter properties (where the expected position equals to 1/`true`)
```
+CBC: 1,2,123456
```
Updated the tests, too.
=>  fix(esp_modem): Fix battery status parser

components/esp_modem/examples/modem_console/main/httpget_handle.c, components/esp_modem/include/cxx_include/esp_modem_types.hpp
Closes #13 
The PR adds explicitly defaulted virtual destructors and explicitly deleted other special member functions for the `ModuleIf` and `CommandableIf` classes to follow the [rule of 5](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-five) and [this guideline](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-copy-virtual).
The second commit also fixes a compilation error from in the `modem_console` example with `-Werror -Wswitch-default` compile options.
=> fix: add virtual destructors to ModuleIf and CommandableIf

components/esp_modem/CMakeLists.txt, components/esp_modem/examples/linux_modem/main/CMakeLists.txt, components/esp_modem/idf_component.yml, components/esp_modem/test/host_test/main/CMakeLists.txt, components/esp_modem/test/target/main/CMakeLists.txt
issue: https://gitlab.kitware.com/cmake/cmake/-/issues/23297
It should work since CMake 3.1 version (https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html)
=> build: fix issue with passing cxx_std option, a common workaround (IDFGH-6876)

components/esp_modem/examples/ap_to_pppos/main/ap_to_pppos.c, components/esp_modem/idf_component.yml
`esp_system.h` does not longer include `esp_mac.h` so it must be included explicitly.
See https://github.com/espressif/esp-idf/commit/a9fda54d39d1321005c3bc9b3cc268d0b7e9f052
=> Fix IDFv5.0 include paths (IDFGH-6972)

components/esp_modem/examples/modem_console/CMakeLists.txt, components/esp_modem/examples/modem_console/README.md, components/esp_modem/examples/modem_console/components/esp_modem_usb_dte/CMakeLists.txt, components/esp_modem/examples/modem_console/components/esp_modem_usb_dte/esp_modem_usb.cpp, components/esp_modem/examples/modem_console/components/esp_modem_usb_dte/esp_modem_usb_api_target.cpp, components/esp_modem/examples/modem_console/components/esp_modem_usb_dte/include/cxx_include/esp_modem_usb_api.hpp, components/esp_modem/examples/modem_console/components/esp_modem_usb_dte/include/esp_modem_usb_config.h, components/esp_modem/examples/modem_console/components/esp_modem_usb_dte/private_include/usb_terminal.hpp, components/esp_modem/examples/modem_console/main/CMakeLists.txt, components/esp_modem/examples/modem_console/main/Kconfig.projbuild, components/esp_modem/examples/modem_console/main/modem_console_main.cpp, components/esp_modem/idf_component.yml, components/esp_modem/include/esp_modem_config.h
This PR extends `modem_console` example with USB DTE on supported targets (ESP32-S2/3) and IDF versions (>=4.4).
Added `esp_modem_usb_dte` component mimics structure of original `esp_modem`.
Tested on ESP32-S2 and Quactel BG96 modem.
---
This PR also contains #21 so the CI would pass
=> Add USB DTE example

components/esp_websocket_client/esp_websocket_client.c
[Redo of espressif/esp-idf pull 8455](https://github.com/espressif/esp-idf/pull/8455)
I dont know why, but the current websocket client implementation keeps emitting a DISCONNECTED event when the host address is simply wrong.
To me it seems more clear that this is an error case and usually you have not been connected before, so emitting a DISCONNECTED doesnt seem right?
Let me know what you think
=> Implement websocket client connect error (IDFGH-7245)

components/esp_modem/examples/simple_cmux_client/main/simple_cmux_client_main.cpp
there is a Typo in the Code. dte not uart_dte
=> typo (IDFGH-7360)

components/esp_modem/src/esp_modem_cmux.cpp, components/esp_modem/src/esp_modem_dce.cpp
* BG96 needs a small pause between CMUX command reception and actual use
of the CMUX mode
* Correct CMUX payload reception to check FT_UIH message type (P/F flag
could be cleared or set)
Closes https://github.com/espressif/esp-protocols/issues/33
=> fix(esp_modem): Correction of switching to CMUX mode

components/esp_modem/include/cxx_include/esp_modem_api.hpp, components/esp_modem/include/cxx_include/esp_modem_command_library.hpp, components/esp_modem/include/cxx_include/esp_modem_dce.hpp, components/esp_modem/include/cxx_include/esp_modem_dce_factory.hpp, components/esp_modem/include/cxx_include/esp_modem_dce_module.hpp, components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/include/generate/esp_modem_command_declare.inc, components/esp_modem/src/esp_modem_api.cpp, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/src/esp_modem_command_library.cpp, components/esp_modem/src/esp_modem_modules.cpp, components/esp_modem/test/host_test/main/test_modem.cpp
- Added lists to esp_modem_command_declare.inc
- Extended command library to include many commonly used AT commands (using simcom modules as a base)
- Added SIM7070, SIM7000 and extended SIM7600 classes
- Tested both C and C++ APIs
- Changed initial modem_mode to be set to UNDEF
- In case of mcu restart without modem restart, which could make the modem be stuck in data mode
=> Feature/extended simcom support (IDFGH-7243)

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
with esp_transport_ssl_crt_bundle_attach(), it is not necessary to
include a specific certificate. other protocol clients, such as
esp_http_client, do the same.
fixes #48
=> feat(websocket): allow users to attach CA bundle (IDFGH-7520)

components/esp_modem/idf_component.yml, components/esp_modem/src/esp_modem_cmux.cpp, components/esp_modem/test/host_test/main/LoopbackTerm.cpp, components/esp_modem/test/host_test/main/LoopbackTerm.h, components/esp_modem/test/host_test/main/test_modem.cpp
Support CMUX with extended (2-byte coded) payload.
Closes https://github.com/espressif/esp-protocols/issues/46
=> esp_modem: Support 2 byte size packets

common_components/protocol_examples_common/CMakeLists.txt, common_components/protocol_examples_common/include/protocol_examples_common.h
Updated to explicitly use esp-eth dependency if needed
* Original commit: espressif/esp-idf@5e19b9c9518ae253d82400ab24b86af8af832425
=> protocol_examples_common: Updated to explicitly use esp-eth dependency if needed

components/esp_modem/include/esp_modem_config.h, components/esp_modem/include/vfs_resource/vfs_create.hpp, components/esp_modem/port/linux/esp_system_protocols_linux/include/driver/uart.h, components/esp_modem/src/esp_modem_term_uart.cpp
This is for example needed when using an external crystal to select
UART_SCLK_XTAL, which fixes uart comm issue when using PM with light
sleep enabled.
=> Allow to customize uart source_clk (IDFGH-7659)

components/esp_websocket_client/Kconfig, components/esp_websocket_client/esp_websocket_client.c
- Remove the unused transport. For example, if the connection is Websocket over TCP, we only need ws and tcp transport, no need wss and ssl transport.
- Make the tx buffer and rx buffer malloc dynamic.
This can save about 3 KB memory when no data send and receive.
=> feat(websocket): Optimize memory size for websocket client init (IDFGH-7357)

.github/workflows/build_asio.yml, components/asio/examples/asio_chat/CMakeLists.txt, components/asio/examples/async_request/CMakeLists.txt, components/asio/examples/socks4/CMakeLists.txt, components/asio/examples/ssl_client_server/CMakeLists.txt, components/asio/examples/tcp_echo_server/CMakeLists.txt, components/asio/examples/udp_echo_server/CMakeLists.txt, components/mdns/tests/test_apps/CMakeLists.txt
Found that asio examples can't be built because can not find asio include files (https://github.com/espressif/esp-protocols/runs/7277980358?check_suite_focus=true)
This change fixes that
=> asio: fix exampels build (IDFGH-7792)

components/esp_modem/examples/ap_to_pppos/main/ap_to_pppos.c, components/esp_modem/examples/ap_to_pppos/main/network_dce.c, components/esp_modem/examples/ap_to_pppos/main/network_dce.cpp, components/esp_modem/examples/ap_to_pppos/main/network_dce.h, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/test/target/main/NetworkDCE.cpp
Update the example to use recover network based on
* Checking if modem replies
* Checking the signal quality (per some hard-coded values -- could be adjusted)
* Restarting the modem (using AT commands -- could use GPIO to hard reset)
* Timeouts if no connection
=> fix(esp_modem): Update ap2ppp example to recover network on disconnection

components/esp_modem/CMakeLists.txt, components/esp_modem/examples/modem_console/main/CMakeLists.txt, components/esp_modem/examples/pppos_client/main/CMakeLists.txt, components/esp_modem/idf_component.yml
This is the first step to fix IDF's format warnings.
IDF has globally enabled compiler option `-Wno-format`. The fix will be in three steps:
1. add `-Wno-format` to affected components
2. disable the global option  `-Wno-format`
3. fix format warnings for each component
=> esp_modem: Ignore format warnings (IDFGH-7760)

components/asio/CMakeLists.txt, components/esp_websocket_client/CMakeLists.txt, components/esp_websocket_client/examples/main/CMakeLists.txt, components/mdns/CMakeLists.txt, components/mdns/examples/main/CMakeLists.txt
I found that some components were missed in https://github.com/espressif/esp-protocols/pull/73
This change fixes that
=> ignore format warnings

components/mdns/mdns_networking_lwip.c
In [_mdns_udp_pcb_write()](https://github.com/espressif/esp-protocols/blob/417591b99ff9abae3265ff66a5e575f3c68f7491/components/mdns/mdns_networking_lwip.c#L333) function, it converts  [esp_ip_addr_t](https://github.com/espressif/esp-protocols/blob/38f6eb963a75e4f6ec2480a3630c09afb756ea61/components/esp_modem/port/linux/esp_netif_linux/include/esp_netif_ip_addr.h#L133) to [ip_addr_t,](https://github.com/espressif/esp-lwip/blob/2c9c531f0a7e0ee536db9de4f9dc54e453712087/src/include/lwip/ip_addr.h#L76) this results in a wrong ip_addr_t when the address is IPv6 and [LWIP_IPV6_SCOPES](https://github.com/espressif/esp-lwip/blob/2c9c531f0a7e0ee536db9de4f9dc54e453712087/src/include/lwip/ip6_addr.h#L61) is undefined. This is because zone attribute is optional in lwip …
=> bugfix: mdns IPv6 address convert error (IDFGH-7772)

components/mdns/mdns.c
According to [RFC 6762](https://datatracker.ietf.org/doc/html/rfc6762#section-18.4):
In response messages for Multicast domains, the Authoritative Answer
bit MUST be set to one (not setting this bit would imply there's some
other place where "better" information may be found) and MUST be
ignored on reception.
The PR removes the check on the AA bit.
=> fix(mdns): ignore authoritative flag on reception (IDFGH-7891)

components/esp_modem/examples/linux_modem/main/modem_main.cpp, components/esp_modem/examples/modem_console/components/esp_modem_usb_dte/esp_modem_usb.cpp, components/esp_modem/examples/simple_cmux_client/main/simple_cmux_client_main.cpp, components/esp_modem/include/cxx_include/esp_modem_dce_factory.hpp, components/esp_modem/include/cxx_include/esp_modem_exception.hpp, components/esp_modem/src/esp_modem_dte.cpp, components/esp_modem/src/esp_modem_netif.cpp, components/esp_modem/src/esp_modem_primitives_freertos.cpp, components/esp_modem/src/esp_modem_term_uart.cpp, components/esp_modem/src/esp_modem_uart.cpp, components/esp_modem/src/esp_modem_uart_linux.cpp, components/esp_modem/src/esp_modem_vfs_socket_creator.cpp, components/esp_modem/src/esp_modem_vfs_uart_creator.cpp
This is useful if exceptions are enabled, but caught internally on C++ API boundary
Closes https://github.com/espressif/esp-protocols/issues/74
=> fix(esp-modem): Add filename/line info to exception message

components/esp_modem/CMakeLists.txt, components/esp_modem/idf_component.yml, components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/include/cxx_include/esp_modem_terminal.hpp, components/esp_modem/src/esp_modem_dte.cpp, components/esp_modem/src/esp_modem_netif.cpp
Allow user to register his DTE error handler. Errors from underlying terminals are forwarded to this DTE error handler.
@david-cermak Currently both `data_term` and `command_term` use the same error handler, is it OK?
=> esp_modem: Expose set_error_cb method

components/mdns/mdns.c
* Returns error if we try to add a service without setting hostname
* Reported here: https://www.esp32.com/viewtopic.php?f=13&t=28981
=> mdns: Fix add_service() to report error if no hostname has been set

components/mdns/mdns.c
This is purely a hygiene fix for something I noticed when trying to chase down a bug. The TTLs are defined in mdns_private.h, but were hardcoded to 2250 in mdns.c. 
- Replaces hardcoded PTR "half-TTL" with `MDNS_ANSWER_PTR_TTL/2` (defined in mdns_private.h)
- Replaces hardcoded TXT "half-TTL" with `MDNS_ANSWER_TXT_TTL/2` (defined in mdns_private.h)
=> Replace hardcoded TTL values with named defines (IDFGH-8113)

components/esp_modem/include/generate/esp_modem_command_declare.inc, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/src/esp_modem_command_library.cpp
1) Updated the C++ API in a2866343, but forgot to fix the C API accordingly
2) Corrected timeouts for some commands (`set_pdp_context()`, `set_radio_state()`)
3) Added an explicit timeout parameter to the `esp_modem_at()`
* Closes https://github.com/espressif/esp-protocols/issues/128
* Closes https://github.com/espressif/esp-protocols/issues/129
=> fix(esp_modem): Make get_operator_name() return also ACT value

components/esp_modem/examples/simple_cmux_client/main/Kconfig.projbuild, components/esp_modem/examples/simple_cmux_client/main/simple_cmux_client_main.cpp, components/esp_modem/include/generate/esp_modem_command_declare.inc
Exit CMUX mode at the end of the *simple_cmux_client* example (as describe in this [comment](https://github.com/espressif/esp-protocols/issues/37#issuecomment-1155727790)).
Here is also two minor fixes (formatting & spelling).
=> esp_modem: Exit CMUX after end of example

components/esp_modem/idf_component.yml, components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/include/esp_private/c_api_wrapper.hpp, components/esp_modem/src/esp_modem_c_api.cpp
**This PR focuses on C API of esp_modem**
**The problem:** C++ API is easily expandable with different types of DTE (such as USB DTE). But C API offers only UART DTE in function `esp_modem_new_dev` with no way of extending this function in C.
**The solution:** Move definitions needed for extending C API to separate header file `include/esp_private/c_api_wrapper.h`. Developers of esp_modem extension can include this file with `#include "esp_private/c_api_wrapper.h"` and implement their own `esp_modem_new_dev_*` function.
**The problem:** C API doesn't offer API to register error callback to Terminal errors.
Composition of esp_modem C wrapper `struct esp_modem_dce_wrap`:
struct esp_modem_dce_wrap -> DCE -> DTE -> Terminal -> error_callback_function
DTE is protected (inaccessible) member of …
=> esp_modem: Allow C API extensions (IDFGH-8368)

components/mdns/mdns.c
Check whether `_mdns_server->hostname` is `_str_null_or_empty` before `strcasecmp`.
=> Prevent crash when hostname is null (IDFGH-8356)

components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/src/esp_modem_dte.cpp, components/esp_modem/src/esp_modem_uart.cpp
* Made lambda to capture `std::function<>` by value (to control lifetime of the functor)
* Wait for a signal (*clear to update*) before modifying on-read callback
=> fix(esp-modem): On read/command callback fixes

components/esp_modem/Kconfig, components/esp_modem/docs/README.md, components/esp_modem/idf_component.yml, components/esp_modem/src/esp_modem_cmux.cpp
fix(esp_modem): CMUX to ignore MSC frames
Otherwise it gets confused with DISC frame and causes trouble when entering
CMUX mode (if device sends MSC requests)
=> (esp_modem): Fix switching to CMUX mode for devices that send `MSC`s

components/esp_modem/examples/modem_console/main/modem_console_main.cpp, components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/include/cxx_include/esp_modem_types.hpp, components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/src/esp_modem_dce.cpp, components/esp_modem/src/esp_modem_dte.cpp
* Adds manual transitions to CMUX
* Adds C-API that allows for user defined AT command with own callback
=> fix(esp-modem): Extend CMUX mode to support manual transitions

components/esp_modem/src/esp_modem_c_api.cpp
This pull request should close #208
If I am not missing anything, it seems like the macro used to generate the C-API creates a signature for `esp_modem_set_baud ` function, but there is no definition for it available anywhere. I added a quick definition, which should solve the problem.
I've compiled some of the examples and used `esp_modem_set_baud` with success with this change.
Thank you for taking your time to review this pull request and have a great day!
=> Added the missing definition for the esp_modem_set_baud function (IDFGH-9181)

components/mdns/idf_component.yml
to publish the latest component per recent fixes.
=> mdns: bump the component version to 1.0.8

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
I have had a stack overflow and could find out which of my many connected websocket clients was the cause, I started giving individual names to all of them using my patch.
=> Add task_name config option (for websocket client) (IDFGH-9346)

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
Add HTTP basic authorization header for websocket client.
The build fail issue depended on ESP-IDF internal MR !22202 to be merged.
=> websocket: Support HTTP basic authorization

components/mdns/mdns.c, components/mdns/private_include/mdns_private.h
PR for https://github.com/espressif/esp-idf/issues/10754
Component should not alter the task notification bits of the calling task.
=> components/mdns: use semaphore instead of task notification bits (IDFGH-9380) (IDFGH-9388)

components/esp_modem/idf_component.yml, components/esp_modem/src/esp_modem_netif.cpp, components/esp_modem/src/esp_modem_netif_linux.cpp, components/esp_modem/src/esp_modem_uart.cpp
* The DTE's on_data callback should return false only if there is a problem with the received data.
* The updated UART Terminal implementation cannot longer clear its callback. It is DTE's responsibility to clear the callback.
As a result, the UART implementation ignores the returned value from on_data callback. However, this feature is important for USB DTE implementation that handles RX data differently.
PTAL @david-cermak
=> esp_modem: Return true from on_data callback in data mode

components/esp_modem/idf_component.yml, components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/include/cxx_include/esp_modem_types.hpp, components/esp_modem/src/esp_modem_dce.cpp, components/esp_modem/src/esp_modem_dte.cpp
Modems can expose 2 terminals, which can be used simultaneously. One for AT commands, the other one for data.
* Added new DTE constructors that accept two instances of `Terminal` class
* Added new DTE state 'DUAL'
Tested with USB modem SimCom A7670E
@david-cermak PTAL
=> esp_modem: Dual DTE support

.github/workflows/pre_commit_check.yml
Regression from  https://github.com/espressif/esp-protocols/pull/242, where I accidentally added `on: push` trigger for the job that's supposed to be run only on PRs.
Introduced in a089e0d6800ad20b090baa32ae033571f93bf198
=> fix(ci): Run pre-commit checker only on PRs

.github/workflows/asio__build-target-test.yml, .github/workflows/mdns__build-target-test.yml, .github/workflows/mdns__host-tests.yml, .github/workflows/modem__build-host-tests.yml, .github/workflows/modem__target-test.yml, .github/workflows/mqtt_cxx__build.yml, .github/workflows/websocket__build-target-test.yml, .pre-commit-config.yaml, CONTRIBUTING.md, ci/changelog.py, components/esp_modem/examples/ap_to_pppos/main/ap_to_pppos.c, components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
* Adds local pre-commit hook to make cz commit messages stricter (allow only listed `type` and `scope`)
* Adds a simple script to compose changelog based on `component` scoped logs
* Adds `mdns` cz-config and bumps the version
=> mdns: Bump config to auto-generate change log

components/esp_modem/examples/modem_console/main/Kconfig.projbuild, components/esp_modem/examples/modem_console/main/idf_component.yml, components/esp_modem/examples/modem_console/main/modem_console_main.cpp, components/esp_modem/examples/pppos_client/main/Kconfig.projbuild, components/esp_modem/examples/pppos_client/main/idf_component.yml, components/esp_modem/examples/pppos_client/main/pppos_client_main.c
Update esp_modem examples for new features in esp_modem_usb_dte v1.1
* Fix: modem_console: Take default apn name from Kconfig
* Use default USB configurations from esp_modem_usb_dte v1.1, including dual DTE SimCom A7670
* https://github.com/espressif/esp-protocols/issues/133
* https://github.com/espressif/esp-protocols/issues/200
=> esp_modem: Update examples for USB v1.1

components/mdns/mdns.c, components/mdns/private_include/mdns_private.h, components/mdns/tests/host_test/components/esp_netif_linux/esp_netif_linux.c
**Description:** When the netif interface with link-local and many routable addresses, If a device query a mDNS service in local network, the ESP-device with mDNS feature responses the query with the link-local address AAAA resource record only in reponsed message.
**Requirement:** The address queries response message should include all ipv6 address accord to the RFC 6762's 6.2 section.
**Related Issue:** IDFGH-9637
=> mdns: append all ipv6 address in mdns answer (IDFGH-9646)

components/mdns/mdns.c
A customer had hundrets of thousands of recorded crashes in the mdns code because answers was a nullptr.
We are inserting all esp crashes in our sentry which has the stack already decoded and ordered by fimrware version, esp-idf version and customer serial number.
I know if I recorded a malicious packet and sent it to espressif I could get a bounty price but I do this for charity now :)
I was too lazy to build a remote packet sniffer for the esp as driving to the customers site was not possible.
=> Fix deadly mdns crash (IDFGH-9800)

.github/workflows/pre_commit_check.yml, .github/workflows/publish-docs-component.yml, CONTRIBUTING.md, ci/bump, ci/changelog.py, ci/detect_component_bump
Alternative to https://github.com/espressif/esp-protocols/pull/276
* `bump` command needs to be executed manually
* tag will be created on master branch (on the Merge commit)
* release will be created
=> ci(common): Support for tagging and releasing in CI

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
- Decouple main module from mdns-networking (d238e93)
- Use idf-build-apps package for building mdns (1a0a41f)
- socket networking to init interfaces properly (ee9b04f)
- Removed unused internal lock from mdns_server struct (a06fb77)
- Resolve conflicts only on self hosted items (e69a9eb, #185)
- Fix memory issues reported by valgrind (0a682e7)
- Add APIs to look up delegated services (87dcd7d)
- Fix deadly mdns crash (4fa3023)
- docs(common): improving documentation (ca3fce0)
- append all ipv6 address in mdns answer (5ed3e9a)
- test(mdns): Host tests to use IDF's esp_event_stub (537d170)
=> bump(mdns): 1.0.9 -> 1.1.0

ci/detect_component_bump
If the merged PR is a few commits behind master, the merge commit could show changes in the version files as well. This fix checks if the version already exists and updates the envirionment only if the tag is not present.
=> ci(common): Update component version only if tag doesn't exist

.github/workflows/publish-docs-component.yml
* Uses https://github.com/espressif/upload-components-ci-action workflow to upload new component version
* Fixes issues with deprecated CLI commands in https://github.com/espressif/esp-protocols/actions/runs/4929072041/jobs/8808238757
* currently used GitHub action is deprecated https://github.com/espressif/github-actions/tree/master/upload_components
=> ci(common): Use upload-components-ci-action workflow action

.github/workflows/mdns__host-tests.yml
* Compilation of our current mDNS host test fails with latest IDF
- IDF now supports FreeRTOS simulator
* Use v5.1 to run the test
* Next step is to use FreeRTOS simulator with latest IDF (TODO in a followup PR)
=> fix(mdns): Run host test against v5.1 instead of latest IDF

components/mdns/mdns.c
Allow mdns to add a delegated host with no address.
=> mdns: allow for adding a delegated host with no address (IDFGH-10246)

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/other-issue.yml
Just updating docs links. Decided to give a common link to the README, rather that listing all the components and docs.
=> Update issue template with correct docs links

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.2.0
Features
- add an API for setting address to a delegated host (ddc3eb6)
- Add support for lwip build under linux (588465d)
- Allow for adding a delegated host with no address (c562461)
- Add APIs for looking up self hosted services and getting the self hostname (f0df12d) Bug Fixes
- Refactor freertos linux compat layers (79a0e57)
- Fix delegated service PTR response (cab0e1d)
- Added unit tests to CI + minor fix to pass it (c974c14) Updated
- docs: update documentation links (4de5298)
=> bump(mdns): 1.1.0 -> 1.2.0

components/mdns/Kconfig, components/mdns/private_include/mdns_private.h, components/mdns/tests/test_afl_fuzz_host/sdkconfig.h
Allow users to configure the length of mDNS action queue via menuconfig.
=> feat(mdns): Allow setting length of mDNS action queue in menuconfig

components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/idf_component.yml
1.0.1
Bug Fixes
- esp_websocket_client client allow sending 0 byte packets (b5177cb)
- Cleaned up printf/format warnings (-Wno-format) (e085826)
- Added unit tests to CI + minor fix to pass it (c974c14)
- Reintroduce missing CHANGELOGs (200cbb3) 
Updated
- docs(common): updated component and example links (f48d9b2)
- docs(common): improving documentation (ca3fce0)
- Fix weird error message spacings (8bb207e)
=> bump(websocket): 1.0.0 -> 1.0.1

.pre-commit-config.yaml, components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/src/esp_modem_dte.cpp
Fixes https://github.com/espressif/esp-protocols/issues/339 (After unsuccessful CMUX initialization, incoming UART data will cause panic.)
Also, I was forced to bump the check-copyright version because I could not run precomit_hooks. The core issue was https://github.com/espressif/check-copyright/pull/10
=> Fix LoadProhibited after failed CMUX initialization

.github/workflows/run-host-tests.yml
Due to docker package upgrade, gcc-8 package is not available. 
Updated gcovr tool to use the latest available one
=> fix(websocket): fix of websocket coverage report generation

components/esp_modem/Kconfig, components/esp_modem/examples/simple_cmux_client/main/simple_cmux_client_main.cpp, components/esp_modem/include/cxx_include/esp_modem_dce_factory.hpp, components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/include/cxx_include/esp_modem_netif.hpp, components/esp_modem/src/esp_modem_dce.cpp, components/esp_modem/src/esp_modem_dte.cpp, components/esp_modem/src/esp_modem_netif.cpp, components/esp_modem/src/esp_modem_uart.cpp
* Simplifies network switching
* Implements inflatable buffer in CMUX and CMD mode
* Sets the ground for URC handling in the library
* Fixes potential data races (adding an extra mutex)
=> fix(modem): Refactor of DTE callbacks (and other fixes)

.github/workflows/modem__build-host-tests.yml, components/esp_modem/examples/modem_tcp_client/CMakeLists.txt, components/esp_modem/examples/modem_tcp_client/README.md, components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/CMakeLists.txt, components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/README.md, components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/include/mbedtls_wrap.hpp, components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/include/tcp_transport_mbedtls.h, components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/mbedtls_wrap.cpp, components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/tls_transport.cpp, components/esp_modem/examples/modem_tcp_client/main/CMakeLists.txt, components/esp_modem/examples/modem_tcp_client/main/Kconfig.projbuild, components/esp_modem/examples/modem_tcp_client/main/modem_client.cpp, components/esp_modem/examples/modem_tcp_client/main/sock_commands.hpp, components/esp_modem/examples/modem_tcp_client/main/sock_commands_bg96.cpp, components/esp_modem/examples/modem_tcp_client/main/sock_commands_sim7600.cpp, components/esp_modem/examples/modem_tcp_client/main/sock_dce.cpp, components/esp_modem/examples/modem_tcp_client/main/sock_dce.hpp, components/esp_modem/examples/modem_tcp_client/main/tcp_transport_at.cpp, components/esp_modem/examples/modem_tcp_client/main/tcp_transport_at.h
* Adds TLS transport utility component
* Adds support for AT based TCP transport
* Example to use TLS over AT based TCP transport
=> feat(modem): Support custom transport in AT TCP client example

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.2.1
Features
- Allow setting length of mDNS action queue in menuconfig (28cd898) 
Bug Fixes
- fix build issue if CONFIG_ESP_WIFI_ENABLED disabled (24f7031)
- added idf_component.yml for examples (d273e10)
- added guard check for null pointer (71bb461)
=> bump(mdns): 1.2.0 -> 1.2.1

components/esp_mqtt_cxx/include/esp_mqtt_client_config.hpp
Event type was introduced in the original version and wasn't used in the code. In 5.1 the leftover type was removed from esp_mqtt breaking this wrapper.
=> fix(mqtt_cxx): Removes unused type for configuration

components/esp_mqtt_cxx/esp_mqtt_cxx.cpp
Information isn't available in the event, so the printf isn't meaningful and can be confusing to users.
=> Remove meaningless print

.github/workflows/modem__build-host-tests.yml, components/esp_modem/include/vfs_resource/vfs_create.hpp, components/esp_modem/src/esp_modem_netif.cpp, components/esp_modem/src/esp_modem_term_fs.cpp
If the config struct contains more items (or more items will be added in
future) this init will not compile cleanly
If the config struct contains more items (or more items will be added in
future) this init will not compile cleanly
=> fix(modem): Update vfs terminal; Removed designated init

components/asio/CMakeLists.txt, components/esp_modem/examples/modem_console/main/CMakeLists.txt, components/esp_modem/examples/modem_console/main/modem_console_main.cpp, components/esp_modem/examples/modem_console/main/ping_handle.c, components/esp_modem/examples/modem_psm/main/CMakeLists.txt, components/esp_modem/examples/modem_tcp_client/main/CMakeLists.txt, components/esp_modem/examples/modem_tcp_client/main/modem_client.cpp, components/esp_modem/examples/modem_tcp_client/main/sock_dce.cpp, components/esp_modem/examples/modem_tcp_client/main/sock_dce.hpp, components/esp_modem/examples/pppos_client/main/CMakeLists.txt, components/esp_modem/examples/pppos_client/main/pppos_client_main.c, components/esp_modem/test/target/main/CMakeLists.txt, components/esp_modem/test/target/main/pppd_test.cpp, components/esp_mqtt_cxx/CMakeLists.txt, components/esp_mqtt_cxx/esp_mqtt_cxx.cpp, components/esp_mqtt_cxx/examples/ssl/main/CMakeLists.txt, components/esp_mqtt_cxx/examples/ssl/main/mqtt_ssl_example.cpp, components/esp_mqtt_cxx/examples/tcp/main/CMakeLists.txt, components/esp_mqtt_cxx/examples/tcp/main/mqtt_tcp_example.cpp, components/mdns/CMakeLists.txt, components/mdns/examples/main/CMakeLists.txt, components/mdns/examples/main/mdns_example_main.c, components/mdns/mdns.c, components/mdns/mdns_networking_socket.c, components/mdns/private_include/mdns_private.h, components/mdns/tests/test_apps/main/CMakeLists.txt, components/mdns/tests/test_apps/main/main.c
In this PR included
-  Fix of CI failure for esp modem host tests
-  Fix of esp_mqtt_cxx target tests
=> fix(common): removed Wno-format flag and fixed formatting warnings (IDFGH-7768)

components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml
- Add factory method for simple creation of custom DCEs (4cf9e50)
- Support custom transport in AT TCP client example (ae629ed)
- Fix host test race with async read and d'structor (c89d42f)
- More error handling in cmux protocol (8edbac6)
- Fix netif to set PPP config in C++ way (5287432)
- Fix vfs terminal not to reset read_cb() automatically (25a35e2)
- Fix netif data race causing PPP startup delays (c8c0507, #308)
- Added support for inflatable buffer (cb6e03a, #272)
- Fix LoadProhibited after failed CMUX initialization (IDFGH-10845) (60c87dd)
=> bump(modem): 1.0.1 -> 1.0.2

components/mdns/Kconfig, components/mdns/mdns.c
The mDNS services is a list so the range of MDNS_MAX_SERVICES is meaningless.
Also fix some issues of str-functions.
=> fix(mdns): remove the range of MDNS_MAX_SERVICES and fix some issues of str-functions

components/mdns/mdns.c
Without this, any use of `_mdns_host_list` risks crashing due to use of freed memory.
=> Fix MDNS free host list (IDFGH-11116)

.github/workflows/console_simple_init__build.yml, .github/workflows/publish-docs-component.yml, .pre-commit-config.yaml, components/console_simple_init/CMakeLists.txt, components/console_simple_init/LICENSE, components/console_simple_init/README.md, components/console_simple_init/console_simple_init.c, components/console_simple_init/console_simple_init.h, components/console_simple_init/examples/console_basic/CMakeLists.txt, components/console_simple_init/examples/console_basic/main/CMakeLists.txt, components/console_simple_init/examples/console_basic/main/console_basic.c, components/console_simple_init/examples/console_basic/main/idf_component.yml, components/console_simple_init/examples/console_basic/pytest_console_basic.py, components/console_simple_init/idf_component.yml
The component provides a simple api's to initialize and start the esp console.
It also provides an api to register an user provided command.
=> feat(common): Added simple component for console initialization

components/esp_modem/src/esp_modem_dte.cpp
In the recent DTE refactoring (cb6e03ac) we install terminal callbacks in the constructor, but the change missed initializing modem_state in DTE constructors which take two terminals as arguments to work in DUAL mode.
=> fix(modem): Fix DUAL_MODE regression from cb6e03ac

ci/detect_component_bump
When we need to version the component metadata the tag creation will not break for the usage of a forbidden character.
=> Fix tag creation

components/esp_mqtt_cxx/.cz.yaml, components/esp_mqtt_cxx/CHANGELOG.md, components/esp_mqtt_cxx/idf_component.yml
0.2.0
Features
- configure client authentication via certificate/key or secure element (ee09ff4) Bug Fixes
- removed Wno-format flag and fixed formatting warnings (c48e442)
- Removes meaningless printf on subscribed handler (#358) (bac742d, #356)
- Removes unused type for configuration (839c79d)
- added idf_component.yml for examples (d273e10)
- Reintroduce missing CHANGELOGs (200cbb3, #235) Updated
- docs(common): updated component and example links (f48d9b2)
- docs(esp_mqtt_cxx): updated documentation and deployment file (a547ec8)
- docs(common): improving documentation (ca3fce0)
- Add homepage URL and License to all components (ef3f0ee)
=> bump(mqtt_cxx): 0.1.0 -> 0.2.0

components/esp_modem/src/esp_modem_dte.cpp
Need the callback reset upon removal of our custom AT command processing. This issue has been introduced in cb6e03ac when refactoring DTE callbacks.
=> fix(modem): Fix AT client example to use custom AT processing

components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml
- Added USB runner with ESP32S2 with A7670 (edeb936)
- Extend docs on AT client example (1f2ceed)
- Fix pytest exclusion, gitignore, and changelog checks (2696221)
- Fix DTE to post fragments to parsers for USB term (1db1e15)
- Fix DUAL_MODE regression from cb6e03ac (2aada0f)
- Fix AT client example to use custom AT processing (1a5ba98, #352)
=> bump(modem): 1.0.3 -> 1.0.4

components/mdns/mdns.c
Currently, the API `mdns_hostname_get` will never copy the terminator `\0`, this PR fix it.
=> fix(mdns): add terminator for the getting host name

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.2.2
Bug Fixes
- add terminator for the getting host name (b6a4d94)
- Enable ESP_WIFI_CONFIG when ESP-IDF <= 5.1 (0b783c0)
- set host list NULL on destroy (ea54eef)
- removed Wno-format flag and fixed formatting warnings (c48e442)
- remove the the range of MDNS_MAX_SERVICES and fix issues of string functions (3dadce2)
=> bump(mdns): 1.2.1 -> 1.2.2

components/console_simple_init/CMakeLists.txt, components/console_simple_init/README.md, components/console_simple_init/console_simple_init.c, components/console_simple_init/console_simple_init.h, components/console_simple_init/examples/console_basic/main/console_basic.c, components/console_simple_init/examples/console_basic/main/idf_component.yml, components/console_simple_init/linker.lf
Added support for runtime component registration in console_simple_init.
=> feat(console): Added runtime component registration support in console_simple_init

components/console_simple_init/.cz.yaml, components/console_simple_init/CHANGELOG.md, components/console_simple_init/idf_component.yml
1.1.0
Features
- Added runtime component registration support in console_simple_init (057873c1)
=> bump(console): 1.0.2 -> 1.1.0

components/asio/CHANGELOG.md, components/asio/CONTRIBUTING.md, components/asio/idf_component.yml
1.28.2~0
Bug Fixes
- reference protocol_examples_common from IDF ([09abb18](https://github.com/espressif/esp-protocols/commit/09abb18))
- specify override_path in example manifest files ([1d8923c](https://github.com/espressif/esp-protocols/commit/1d8923c))
Updated
- docs(asio): Updates asio docs ([ce9337d](https://github.com/espressif/esp-protocols/commit/ce9337d))
=> bump(asio): 1.28.0~0 -> 1.28.2~0

components/esp_modem/CMakeLists.txt, components/esp_modem/Kconfig, components/esp_modem/examples/pppos_client/main/Kconfig.projbuild, components/esp_modem/examples/pppos_client/main/custom_module.hpp, components/esp_modem/examples/pppos_client/main/pppos_client_main.c, components/esp_modem/include/cxx_include/esp_modem_dce_factory.hpp, components/esp_modem/include/cxx_include/esp_modem_types.hpp, components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/include/generate/esp_modem_command_declare.inc, components/esp_modem/src/esp_modem_c_api.cpp, docs/esp_modem/en/README.rst
* It's now possible to inject custom module's DCEs into C-API
* added a demonstration config for custom modules in `pppos_client` example
* fixed CR/LF issue
=> Added support for implementing user defined modules in standard C-API

components/esp_modem/examples/pppos_client/main/pppos_client_main.c, components/esp_modem/test/target/main/pppd_test.cpp
The event data is a pointer to netif, need to deference to correctly display the `esp_netif` handle.
https://github.com/espressif/esp-idf/blob/c8243465e45489835d645bf217a6929fd0c01b7f/components/esp_netif/lwip/esp_netif_lwip_ppp.c#L104
=> fix(modem): Fixed examples to show netif on ppp-changed event

components/asio/examples/asio_chat/CMakeLists.txt, components/asio/examples/asio_chat/main/idf_component.yml, components/asio/examples/async_request/CMakeLists.txt, components/asio/examples/async_request/main/idf_component.yml, components/asio/examples/socks4/CMakeLists.txt, components/asio/examples/socks4/main/idf_component.yml, components/asio/examples/ssl_client_server/CMakeLists.txt, components/asio/examples/ssl_client_server/main/idf_component.yml, components/asio/examples/tcp_echo_server/CMakeLists.txt, components/asio/examples/tcp_echo_server/main/idf_component.yml, components/asio/examples/udp_echo_server/CMakeLists.txt, components/asio/examples/udp_echo_server/main/idf_component.yml, components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/examples/linux/CMakeLists.txt, components/esp_websocket_client/examples/linux/main/idf_component.yml, components/esp_websocket_client/examples/target/CMakeLists.txt, components/esp_websocket_client/examples/target/main/idf_component.yml, components/esp_websocket_client/idf_component.yml
In order to publish `v1.2.0` version of websocket client.
* This is needed as the local references in `idf_component.yml` are not supported yet
* This picks @gabsuren 's bump of ws client from https://github.com/espressif/esp-protocols/pull/437
=> Temporarily revert IDF component references in examples

components/esp_modem/examples/modem_console/main/modem_console_main.cpp, components/esp_modem/src/esp_modem_dce.cpp, components/esp_modem/src/esp_modem_dte.cpp, components/esp_modem/test/host_test/main/test_modem.cpp, docs/esp_modem/en/README.rst
Closes https://github.com/espressif/esp-protocols/issues/320
=> fix(modem): Fixed mode transitions between any state and UNDEF

components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/include/mbedtls_wrap.hpp, components/esp_modem/examples/modem_tcp_client/components/extra_tcp_transports/mbedtls_wrap.cpp
Reusable component in modem_tcp_client example implements a simple mbedtls wrapper. This update add support for mbedtls deinit() and for saving and resotoring TLS session.
=> fix(modem): TLS example: Add restore session support in mbedtls wrapper

components/asio/examples/asio_chat/CMakeLists.txt, components/asio/examples/async_request/CMakeLists.txt, components/asio/examples/async_request/main/idf_component.yml, components/asio/examples/socks4/CMakeLists.txt, components/asio/examples/socks4/main/idf_component.yml, components/asio/examples/ssl_client_server/CMakeLists.txt, components/asio/examples/ssl_client_server/main/idf_component.yml, components/asio/examples/tcp_echo_server/CMakeLists.txt, components/asio/examples/tcp_echo_server/main/idf_component.yml, components/asio/examples/udp_echo_server/CMakeLists.txt, components/asio/examples/udp_echo_server/main/idf_component.yml, components/esp_websocket_client/examples/linux/CMakeLists.txt, components/esp_websocket_client/examples/linux/main/idf_component.yml, components/esp_websocket_client/examples/target/CMakeLists.txt, components/esp_websocket_client/examples/target/main/idf_component.yml
Re-applied the references to `idf_component.yml` after merging https://github.com/espressif/esp-protocols/pull/440 to publish websocket client
* This reverts commit 74fc228cdfa6de07892118210505661f9d4ae837. 
* This reverts commit b176d3abbb741a8b77ae564cc93cfad72b440f94.
* This reverts commit f9e0281a04b7370ad4ba9c0b9cdf590bbf4475f6.
=> fix(common): Re-applied refs to common comps idf_component.yml

.github/workflows/console_cmd_ifconfig__build.yml, .github/workflows/publish-docs-component.yml, CONTRIBUTING.md, README.md, components/console_cmd_ifconfig/.cz.yaml, components/console_cmd_ifconfig/CHANGELOG.md, components/console_cmd_ifconfig/CMakeLists.txt, components/console_cmd_ifconfig/LICENSE, components/console_cmd_ifconfig/README.md, components/console_cmd_ifconfig/console_ifconfig.c, components/console_cmd_ifconfig/console_ifconfig.h, components/console_cmd_ifconfig/examples/ifconfig-basic/CMakeLists.txt, components/console_cmd_ifconfig/examples/ifconfig-basic/main/CMakeLists.txt, components/console_cmd_ifconfig/examples/ifconfig-basic/main/idf_component.yml, components/console_cmd_ifconfig/examples/ifconfig-basic/main/ifconfig-basic.c, components/console_cmd_ifconfig/examples/ifconfig-basic/pytest_ifconfig-basic.py, components/console_cmd_ifconfig/idf_component.yml
Console for runtime network interface configuration and monitoring.
=> Added component: Console for runtime network interface configuration

components/esp_modem/src/esp_modem_dte.cpp
If we received response in two chunks and the first one completed the command (result=OK or FAIL), and the second chunk preempts command processing, then we performed processing again rewriting the result back to TIMEOUT. This would invalidate the command, but also causes an exception: `ESP_MODEM_THROW_IF_ERROR(ESP_ERR_INVALID_STATE)`
Fixed by checking if the processing already finished in process_line().
Closes https://github.com/espressif/esp-protocols/issues/426
=> fix(modem): Fixed inconsistent state on data after OK

components/esp_modem/test/host_test/main/test_modem.cpp
This test exhibits an issue of getting unexpected data just after completing a command. The DTE rewrites the state to TIMEOUT, but the signal has been already triggered, thus results in an unexpected state.
Related to Closes https://github.com/espressif/esp-protocols/issues/426
=> fix(modem): Added test injecting unexpected replies

components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml
- Added support for implementing user defined modules in standard C-API (Support for custom modules with C-API)
- Added test injecting unexpected replies (b220d1e, #426)
- Fixed inconsistent state on data after OK (bf99f28, #426)
- TLS example: Added restore session support in mbedtls-wrap (79d38e5)
- Fixed examples to show netif on ppp-changed event (a70b197)
- remove unused GNU Make based buildsystem files (d6b6f63)
- specify override_path in example manifest files (5b78da4)
- Added test-cases that exercise mode transitions (aff571d)
- Fixed mode transitions between any state and UNDEF (93cb2ca, #320)
- Fixed API docs within doxygen comments (020b407)
- Support for custom modules with C-API (0254d50)
- Fix CRLF issue with esp_modem_c_api.cpp (2661b4d)
- ci(common): Created reusable …
=> bump(modem): 1.0.4 -> 1.0.5

components/esp_websocket_client/esp_websocket_client.c
=> fix: continuation after FIN in websocket client (#460) (IDFGH-11761)

.github/workflows/console_cmd_wifi__build.yml, .github/workflows/publish-docs-component.yml, components/console_cmd_ifconfig/console_ifconfig.c, components/console_cmd_wifi/.cz.yaml, components/console_cmd_wifi/CHANGELOG.md, components/console_cmd_wifi/CMakeLists.txt, components/console_cmd_wifi/README.md, components/console_cmd_wifi/console_wifi.c, components/console_cmd_wifi/console_wifi.h, components/console_cmd_wifi/examples/wifi-basic/CMakeLists.txt, components/console_cmd_wifi/examples/wifi-basic/main/CMakeLists.txt, components/console_cmd_wifi/examples/wifi-basic/main/idf_component.yml, components/console_cmd_wifi/examples/wifi-basic/main/wifi-basic.c, components/console_cmd_wifi/examples/wifi-basic/pytest_wifi-basic.py, components/console_cmd_wifi/idf_component.yml
Added a component that offers a console with a command that enables runtime wifi configuration for any example project.
=> feat(console): Console for runtime wifi configuration

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.2.3
Bug Fixes
- fixed CI issues for host and afl tests (4be5efc84e)
- fix copy delegated host addr (19fb36000c)
- enable CONFIG_ESP_WIFI_ENABLED if CONFIG_SOC_WIFI_SUPPORTED is also enabled (for ESP-IDF <= 5.1) (d20a718320)
- remove protocol_examples_common (1ee9dae6bf)
- move the example into a subdirectory (d28232b9f8)
- reference protocol_examples_common from IDF (c83b76ea8f)
=> bump(mdns): 1.2.2 -> 1.2.3

examples/esp_netif/slip_custom_netif/components/slip_modem/library/slip_modem_netif.c
`esp_netif_next()` is deprecated from `v5.2`
=> fix(examples): Fixed esp_netif_next() warning with IDFv5.3

components/mdns/mdns.c
This is a fix for the issue #459.
=> fix(mdns): Fix compile error when MDNS_PREDEF_NETIF_ETH is defined, but ETH_ENABLED is not (IDFGH-11868)

components/esp_modem/include/cxx_include/esp_modem_command_library_utils.hpp, components/esp_modem/src/esp_modem_command_library.cpp
Previously we used std::string_view, which pointed to the lower-layers buffer which might have been reused for other asynchronous operations before processing it, thus causing corruption of replies.
Closes https://github.com/espressif/esp-protocols/issues/463
=> fix(modem): Fixed AT commands to copy strings to prevent overrides

components/mdns/mdns.c
Fixes after 6d2c475c2039e57c83c7fe2b679b18501405c9de, which used incorrect config option name `CONFIG_MDNS_NETIF_ETH` (instead of `MDNS_PREDEF_NETIF_ETH`).
Causing master pipeline to fail in https://github.com/espressif/esp-protocols/actions/runs/7553595066/job/20566133750
=> fix(mdns): Correction on 6d2c475 MDNS_PREDEF_NETIF_ETH fix

docs/esp_modem/en/README.rst
Closes https://github.com/espressif/esp-protocols/issues/482
=> fix(modem): Documented some tips on failing OTA

components/esp_mqtt_cxx/.cz.yaml, components/esp_mqtt_cxx/CHANGELOG.md, components/esp_mqtt_cxx/idf_component.yml
0.3.0
Bug Fixes
- Incorrect documentation link (aa4e9d57)
- reference protocol_examples_common from IDF (e6c0538d)
- specify override_path in example manifest files (fa005c63)
=> bump(mqtt_cxx): 0.2.0 -> 0.3.0

components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/idf_component.yml
1.2.2
Bug Fixes
- continuation after FIN in websocket client (#460) (774d1c75e6)
- Re-applied refs to common comps idf_component.yml (9fe44a4504)
=> bump(websocket): 1.2.1 -> 1.2.2

components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml
- Added support for at_raw() command (ae38110, #471)
- Added iperf test for PPP netifs (976e98d)
- Added test that performs OTA to exercise modem layers (f2223dd)
- Fixed OTA test to gracefully fail with no verification (1dc4299)
- Added C-API to configure APN (ce7dadd, #485)
- Fixed AT commands to copy strings to prevent overrides (741d166, #463)
- Fixed incorrect dial command format (0998f3d, #433)
- Fixed documentation and example on creating custom device (577de67, #452)
- Removed CI jobs for IDF v4.2 (d88cd61)
- Fixed OAT test to verify server cert and CN (edc3e72)
- Fixed set_pdp_context() command timeout (1d80cbc, #455)
- docs(modem): Added description of manual test procedure (68ce794)
=> bump(modem): 1.0.5 -> 1.1.0

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.2.4
Bug Fixes
- Correction on 6d2c475 MDNS_PREDEF_NETIF_ETH fix (fc59f87c4e)
- fix the logic of creating pcb for networking socket (5000a9a20a)
- fix compiling issue when disabling IPv4 (2646dcd23a)
- Fix compile error when MDNS_PREDEF_NETIF_ETH is defined, but ETH_ENABLED is not (#459) (6d2c475c20)
=> bump(mdns): 1.2.3 -> 1.2.4

components/esp_websocket_client/esp_websocket_client.c
An issue was observed where the websocket client did not send WEBSOCKET_EVENT_CLOSED after server closed the websocket.
An alternative solution to fix the issue would be  to remove the if instead. It could be more robust, but the existing comment seem to suggest that it was not the original intent.
=> fix(websocket): Continue waiting for TCP connection to be closed (IDFGH-11965)

components/esp_websocket_client/esp_websocket_client.c
Fixes crash when using ws Tx functions if `CONFIG_ESP_WS_CLIENT_ENABLE_DYNAMIC_BUFFER=y`
=> [ws-client]: Fix usage of the dynamic buffer

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.2.5
Bug Fixes
- Fixed build issues for targets without WiFi caps (302b46f)
=> bump(mdns): 1.2.4 -> 1.2.5

components/mdns/mdns.c
There is a risk in this scenario:
A pending tx packets (called by the action ACTION_TX_HANDLE) which has a list of answer, while the host will be valid when the packet is created, but the host will be invalid while the packet is sending. We should double check the host is still valid when appending the answer to the packets.
This PR fix this risk.
=> fix(mdns): fix mdns answer append while host is invalid

components/mdns/mdns.c
This PR fixes a thread-safe risk, some common apis do not take a look when operate the static global variable `_mdns_server` of mdns.
=> fix(mdns): add lock for some common apis (IDFGH-12338)

components/esp_modem/examples/pppos_client/main/Kconfig.projbuild, components/esp_modem/examples/simple_cmux_client/components/SIM7070_gnss/SIM7070_gnss.cpp, components/esp_modem/examples/simple_cmux_client/components/SIM7070_gnss/SIM7070_gnss.hpp, components/esp_modem/examples/simple_cmux_client/components/SIM7070_gnss/sim70xx_gps.h
This PR accepts some older modem PRs:
* https://github.com/espressif/esp-protocols/pull/246
* https://github.com/espressif/esp-protocols/pull/245
* https://github.com/espressif/esp-protocols/pull/403
=> [esp_modem]: Accept some PRs

components/esp_websocket_client/CMakeLists.txt
Move esp_event from PRIV_REQUIRES to REQUIRES, as it is included by esp_websocket_client.h, so any code including that header also requires esp_event.
This resolves the following build error for files not explicitly requiring esp_event:
ninja: build stopped: subcommand failed.
Compilation failed because esp_websocket_client.h (in "espressif__esp_websocket_client" component) includes esp_event.h, provided by esp_event component(s). However, esp_event component(s) is in the private requirements list of "espressif__esp_websocket_client". To fix this, move esp_event from PRIV_REQUIRES into REQUIRES list of idf_component_register call in ...\managed_components\espressif__esp_websocket_client\CMakeLists.txt. ninja failed with exit code 1, output of the command is in...
=> fix(websocket): fix esp_event dependency management (IDFGH-12301) (IDFGH-12302)

components/mdns/mdns.c
Instead of processing only one Tx packet at a time, goes over all in the linked list and queue all of them if `send_at` field indicates it should be sent.
Partially addresses: https://github.com/espressif/esp-idf/issues/13333
=> fix(mdns): Schedule all queued Tx packets from timer task

components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/idf_component.yml
1.2.3
Features
- Expanded example to demonstrate the transfer over TLS (0d0630ed76)
Bug Fixes
- fix esp_event dependency management (1fb02a9a60)
- Skip warn on zero timeout and auto reconnect is disabled (5b467cbf5c)
- Fixed to use int return value in Tx functions (9c54b72e1f)
- Fixed Tx functions with DYNAMIC_BUFFER (16174470ee)
- added dependency checks, sdkconfig.defaults and refined README.md (312982e4aa)
- Close websocket and dispatch event if server does not close within a reasonable amount of time. (d85311880d)
- Continue waiting for TCP connection to be closed (2b092e0db4) Updated
- docs(websocket): Added README for websocket host example (2f7c58259d)
=> bump(websocket): 1.2.2 -> 1.2.3

.github/workflows/publish-docs-component.yml, README.md
Just to publish the same version to component manager. Doesn't need a bump commit or newer version, since it's been tagged and released here with `v.0.1.12`
=> fix(wifi_remote): Publish missing esp_wifi_remote and add to README

components/mdns/include/mdns.h, components/mdns/mdns.c, components/mdns/private_include/mdns_private.h
This MR introduces a new query mode: browse(like the `avahi-browse -r _test._tcp`).
`mdns_browse_new` is used for starting a browse, it will add a browse in the link list of `_mdns_server`, if there is some service start or leave, it will be notified by the callback passed in the API. When the service is leaved, the ttl will be `0`, the related result will be freed after syncing to the notifier callback.
`mdns_browse_delete` is used for stop the browse query and free the related memory.
All apis are followed the mdns action mechanism.
=> mdns add browse support (IDFGH-12512)

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.3.0
Features
- add a new mdns query mode `browse` (af330b6)
- Make including mdns_console KConfigurable (27adbfe) 
Bug Fixes
- Schedule all queued Tx packets from timer task (d4e693e)
- add lock for some common apis (21c84bf)
- fix mdns answer append while host is invalid (7be16bc)
=> bump(mdns): 1.2.5 -> 1.3.0

components/esp_modem/src/esp_modem_uart.cpp
If we're missing an UART DATA event, or more data than we read are coming from one event, we would never get another event with the buffered data.
Checking the data periodically (every 100ms) if no event's coming.
https://github.com/espressif/esp-protocols/issues/536
=> fix(modem): Fixed UART task to check for buffered data periodically

components/esp_mqtt_cxx/esp_mqtt_cxx.cpp
Some aspects of the underlying mqtt client were not set.
=> Adds missing configuration fields

.github/workflows/console_cmd_ifconfig__build.yml, components/eppp_link/examples/host/CMakeLists.txt, components/eppp_link/examples/host/main/idf_component.yml, components/esp_modem/.build-test-rules.yml, components/esp_modem/test/target_iperf/CMakeLists.txt, components/esp_modem/test/target_iperf/main/idf_component.yml, components/esp_modem/test/target_iperf/main/pppd_iperf_main.c
Fixes recent incompatibilities with latest IDF (v5.3)
* Moving `iperf` out of IDF
* ESP32P4 is supported target
* warning: the choice symbol ETHERNET_PHY_... has no prompt
*
=> Fix CI build per IDFv5.3

components/eppp_link/.cz.yaml, components/eppp_link/CHANGELOG.md, components/eppp_link/Kconfig, components/eppp_link/idf_component.yml
- Added CI job to build examples and tests ([7eefcf0](https://github.com/espressif/esp-protocols/commit/7eefcf0))
- Fixed to select PPP LWIP opts which are OFF by default ([16be2f9](https://github.com/espressif/esp-protocols/commit/16be2f9))
- Example to use iperf component from the registry ([bd6b66d](https://github.com/espressif/esp-protocols/commit/bd6b66d))
- Fixed defalt config designated init issue in C++ ([8bd4712](https://github.com/espressif/esp-protocols/commit/8bd4712))
=> [eppp]: Force the `PPP` LWIP opts which are OFF by default

components/mdns/mdns.c
Free the new malloced txt_value_len instead of the txt_value_len in search result. If there exits txt entry in query results, the origin free processing will lead a crash due to multi free.
=> fix(mdns): free txt value len (IDFGH-12817)

.github/workflows/clang-tidy.yml
Cherry-picked Ivan's commit from extra-comonents repo:
[ci: remove libtinfo5 installation step](https://github.com/espressif/idf-extra-components/commit/ab23c2bebcf7a6fc3471da595758bbc2c16ad8bd)
=> CI: Fixed clang-tidy job

.github/workflows/wifi_remote__build.yml, components/esp_wifi_remote/eppp/wifi_remote_rpc_client.cpp, components/esp_wifi_remote/eppp/wifi_remote_rpc_server.cpp, components/esp_wifi_remote/examples/test_certs/generate_test_certs.sh
Now we can use any kind of certificate and keys, as long as they're in PEM format.
Closes https://github.com/espressif/esp-protocols/issues/570
=> fix(wifi_remote): Do not restrict EPPP config to RSA keys only

components/mdns/mdns.c
1. Upon receiving a PTR query, when matching question and answer entries, if an instance exists in the answer entry, it will also be considered as one of the check items. This change is to avoid mistakenly deleting certain question entries. For example, if device A hosts services B with the different instances (ins1~ins5). When the device receives a PTR query, with the question querying service B, and the answer list already contains ins1.Service B and ins2.Service B, then when matching this question entry and answer entries, the question entry should not be deleted.
2. Check the answer entries in the query when creating answer entries for query response. If the answer entry already exists, then give up creating that entry.
=> feat(mdns): add check of instance when handling PTR query (IDFGH-12701)

components/mdns/mdns.c, components/mdns/private_include/mdns_private.h
ESP-Matter may publish services with the same protocol and service type but different instance names. e.g., ''a.matter._tcp" and "b.matter._tcp". When service info changed, we have to remove all "matter._tcp" service through `mdns_service_remove(const char *service_type, const char *proto)` and re-add new service. But now, the the different instance name services can not be removed at the same time. And re-adding will lead a **memory leak** problem for the unremoved services with the same subtype.
1. Modify remove services action to remove the same instance name services. 
2. Verify that the service already has the same subtype before adding.
=> fix(mdns): remove same protocol services with different instances

components/esp_wifi_remote/.cz.yaml, components/esp_wifi_remote/CHANGELOG.md, components/esp_wifi_remote/CMakeLists.txt, components/esp_wifi_remote/eppp/wifi_remote_rpc_impl.hpp, components/esp_wifi_remote/eppp/wifi_remote_rpc_params.h, components/esp_wifi_remote/eppp/wifi_remote_rpc_server.cpp, components/esp_wifi_remote/idf_component.yml
Fixes race condition of simultaneously marshaling WiFi/IP event and receiving command from client.
* 9e13870 fix(wifi_remote): Lock server before marshaling events --> Quick and simple fix, but may block default event task
* 30a5262 Fix server event/command race condition using eventfd --> More elaborate and correct fix
=> [wifi-remote]: Fix server race when receiving command and posting events

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
1.3.2
Features
- add check of instance when handling PTR query (6af6ca5) 
Bug Fixes
- Fix of mdns afl tests (139166c)
- remove same protocol services with different instances (042533a)
=> bump(mdns): 1.3.1 -> 1.3.2

.github/workflows/run-host-tests.yml, components/esp_modem/include/cxx_include/esp_modem_cmux.hpp, components/esp_modem/include/cxx_include/esp_modem_netif.hpp, components/esp_modem/src/esp_modem_cmux.cpp, components/esp_modem/src/esp_modem_netif.cpp, components/esp_modem/src/esp_modem_netif_linux.cpp, components/esp_modem/src/esp_modem_term_fs.cpp, components/esp_modem/src/esp_modem_vfs_uart_creator.cpp
* [private field 'netif' is not used [clang-diagnostic-unused-private-field]](https://github.com/espressif/esp-protocols/security/code-scanning/1)
* [private field 'instance' is not used [clang-diagnostic-unused-private-field]](https://github.com/espressif/esp-protocols/security/code-scanning/2)
* [Call to virtual method 'FdTerminal::stop' during destruction bypasses virtual dispatch [clang-analyzer-optin.cplusplus.VirtualCall]](https://github.com/espressif/esp-protocols/security/code-scanning/3)
* [unused variable 'TAG' [clang-diagnostic-unused-const-variable]
](https://github.com/espressif/esp-protocols/security/code-scanning/15)
* [Null pointer passed as 2nd argument to memory copy function [clang-analyzer-unix.cstring.NullArg]](https://github.com/espressif/esp-protocols/security/code-s …
=> [modem]: Fixes clang-tidy warnings

.github/workflows/pre_commit_check.yml, .pre-commit-config.yaml
The previous version (c00138088) required pyyaml 3.0.0 which is broken on certain plafroms (e.g. Fedora 39)
Closes https://github.com/espressif/esp-protocols/issues/592
=> fix(common): Fix pre-commit hook to use released astyle_py

components/esp_wifi_remote/esp_wifi_remote_net.c
Add esp_wifi_internal_tx_by_ref as building with `CONFIG_SPIRAM=y` will get a linker error caused by an undefined reference to the function.
=> feat(wifi_remote): add esp_wifi_internal_tx_by_ref

components/eppp_link/CMakeLists.txt, components/eppp_link/Kconfig, components/eppp_link/README.md, components/eppp_link/eppp_link.c, components/eppp_link/eppp_sdio.h, components/eppp_link/eppp_sdio_host.c, components/eppp_link/eppp_sdio_slave.c, components/eppp_link/examples/host/main/app_main.c, components/eppp_link/examples/slave/main/eppp_slave.c, components/eppp_link/idf_component.yml, components/eppp_link/include/eppp_link.h
Simple connectivity usecase of *eppp_link* on P4-C6 board
=> [eppp]: Add support for SDIO transport

components/eppp_link/.cz.yaml, components/eppp_link/CHANGELOG.md, components/eppp_link/eppp_sdio_host.c, components/eppp_link/eppp_sdio_slave.c, components/eppp_link/idf_component.yml
- Add support for SDIO transport (085dd790)
- Fixed strict prototype API decl issue in SDIO (452e4614)
- Fix SIDO host to check/clear interrupts atomically (402176c9)
=> bump(eppp): 0.1.1 -> 0.2.0

components/esp_mqtt_cxx/.cz.yaml, components/esp_mqtt_cxx/CHANGELOG.md, components/esp_mqtt_cxx/idf_component.yml
0.4.0
Bug Fixes
- Adds missing configuration fields (d4c6d5ed)
=> bump(mqtt_cxx): 0.3.0 -> 0.4.0

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
Currently automatic reconnect interval can only be configured when initializing `esp_websocket_client` and cannot be changed later. This makes it impossible to implement connection retry back-off, for example.
This pull request adds `esp_websocket_client_get_reconnect_timeout()` and `esp_websocket_client_set_reconnect_timeout()` functions.
=> feat(esp_websocket_client): allow updating reconnect timeout for retry backoffs (IDFGH-13016)

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
Set a common name that is verified. We use this via a server using a custom certificate bundle + common name combo.
I am not really sure if we need to deny when `skip_common_name && cert_common_name` is set.
=> feat(websocket_client): Add option to set and use cert_common_name in Websocket client (IDFGH-12926)

components/esp_websocket_client/esp_websocket_client.c
This is a follow up on https://github.com/espressif/esp-protocols/pull/555; `if_name` as not set for WSS while it is for WS. This fixes that. Thanks for considering.
=> feat(websocket): adding support for `if_name` when using WSS transport

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
Hi there,
This PR was originally done last year (May 2023), but I forgot to submit it... 😅 
Anyway, this PR is for adding support to let WebSocket client to take external handles, similar to my another PR for MQTT client, see:
- https://github.com/espressif/esp-mqtt/blob/master/include/mqtt_client.h#L339
- https://github.com/espressif/esp-mqtt/pull/260
This is very useful for scenarios where: 
1. The application requires proxies to access network (via my [esp_tcp_transport_addons](https://github.com/huming2207/esp_tcp_transport_addons) hack for HTTP proxy access, or a SOCK4 proxy via the `transport_socks_proxy.c` in `tcp_transport` component) ;
2. The application somehow requires external TCP/IP stack on a modem via serial port, see [this …
=> feat(websocket): allow using external TCP transport handle (IDFGH-12825)

components/console_cmd_ping/.cz.yaml, components/console_cmd_ping/CHANGELOG.md, components/console_cmd_ping/CMakeLists.txt, components/console_cmd_ping/Kconfig.projbuild, components/console_cmd_ping/README.md, components/console_cmd_ping/console_getaddrinfo.c, components/console_cmd_ping/console_getsetdnsserver.c, components/console_cmd_ping/console_ping.c, components/console_cmd_ping/console_ping.h, components/console_cmd_ping/idf_component.yml
Added command getaddrinfo, setdnsserver, getdnsserver to console_cmd_ping component.
Removed WHOLE_ARCHIVE from CMakelist, and allows users to disable auto-registration of console_cmd_ping component.
=> feat(console): Added command getaddrinfo, set/get dnsserver to console_cmd_ping

components/mdns/mdns.c, components/mdns/mdns_console.c, components/mdns/tests/host_test/components/esp_netif_linux/esp_netif_linux.c, components/mdns/tests/host_test/dnsfixture.py, components/mdns/tests/host_test/pytest_mdns.py
Followup on https://github.com/espressif/esp-protocols/pull/617 for easier reviewing.
Adds simple functional tests for all the below APIs, one commit per item.
=> [mdns]: More console tests

components/mdns/mdns.c, components/mdns/tests/unit_test/main/test_mdns.c
* adding/removing services
* updating service properties (instance, port, txt)
* for selfhosted and delegated services
=> [mdns]: Add unit test for services

components/esp_websocket_client/esp_websocket_client.c
Even though the `esp_tls_stack_err` and `esp_tls_cert_verify_flags` are get, they are not propagated through event data. This fixes that.
I came across this because I noticed that an Mbed TLS error code that I was interested in (`MBEDTLS_ERR_SSL_ALLOC_FAILED`) was correctly logged by the component, but `esp_tls_stack_err` was uninitialized.
=> feat(websocket): propagate esp_tls stack error and cert verify flags

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/examples/linux/main/websocket_linux.c, components/esp_websocket_client/examples/target/main/websocket_example.c, components/esp_websocket_client/include/esp_websocket_client.h, docs/esp_websocket_client/en/index.rst
Add two new events to signal the start and end of websocket thread operation.
Also update the websocket event handler documentation, as it was missing a few.
=> Feat/websocket: begin end thread events (IDFGH-13507)

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
- Fixed mdns API issues when add/remove/update records from multiple threads ([Fix services API races to directly add/remove services](https://github.com/espressif/esp-protocols/commit/8a690503))
- Unit tests for add/remove/update deleg/selfhosted services ([0660ece1](https://github.com/espressif/esp-protocols/commit/0660ece1))
- Add console command for mdns browsing ([1e8ede33](https://github.com/espressif/esp-protocols/commit/1e8ede33))
- Console test: set instance for service ([f107dcd1](https://github.com/espressif/esp-protocols/commit/f107dcd1))
- Console test: add subtype for service ([ee00e97b](https://github.com/espressif/esp-protocols/commit/ee00e97b))
- Console test: set port for (delegated) srvs ([07b79abf](https://github.com/espressif/esp-protocols/commit/07b79abf))
- Console …
=> [mdns]: Bump: 1.3.2 -> 1.4.0

components/mdns/mdns.c
Fixes CID 467738: Logically dead code in mdns.c, _copy_mdns_txt_items
Introduced by probably by a merge confilict, as the fix was added in
two separate PRs, merging d4da9cb0 first and 8a690503 later
Fixes CID 467739: Use after free in mdns.c, mdns_service_remove_for_host
We should look only for one match in the service list, since if we
assume there could be aliases, we might free one and reference the
other.
=> [mdns]: Fix recent issues on v1.4 reported by Coverity

components/esp_modem/Kconfig, components/esp_modem/examples/pppos_client/main/custom_module.hpp, components/esp_modem/src/esp_modem_c_api.cpp, docs/esp_modem/en/api_docs.rst
This PR introduce ability to change ESP_MODEM_C_API_STR_MAX from Kconfig (idf.py menuconfig).
In esp_modem in C-API there is ESP_MODEM_C_API_STR_MAX which defines max size of AT response returned to user.
There is no obvious way to increase this size. Some workaround was found in #184, but I think use Kconfig option is more clear and straightforward.
#184
#624
---
=> [modem]: Add ability to change ESP_MODEM_C_API_STR_MAX from Kconfig (IDFGH-13668)

components/esp_modem/Kconfig, components/esp_modem/include/cxx_include/esp_modem_dce.hpp, components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/src/esp_modem_dte.cpp, components/esp_modem/test/target/main/CMakeLists.txt, components/esp_modem/test/target/main/pppd_test.cpp
Closes https://github.com/espressif/esp-protocols/issues/180
=> [modem]: Add support for handling URC

components/esp_modem/include/generate/esp_modem_command_declare_helper.inc
This PR fixes arguments names which auto-declared by `DECLARE_ALL_COMMAND_APIS()` (`"include/generate/esp_modem_command_declare.inc"`). This time with clean commit history.
For example, it would be:
`esp_err_t esp_modem_send_sms(esp_modem_dce_t *dce, const char *number, const char *message);`
instead of:
`esp_err_t esp_modem_send_sms(esp_modem_dce_t *dce, const char *p1, const char *p2);`
Also, it does clear auto completions and tips in IDE (VS Code + ESP-IDF):
=> [modem]: Fix arguments names when spawn esp_modem_xxx declarations

components/esp_modem/src/esp_modem_dte.cpp
Fix to support forced transitions from CMUX mode to command mode as per the issue "Force exit CMUX does not actually work (IDFGH-13724) https://github.com/espressif/esp-protocols/issues/650"
=> [modem] Minor change to exit_cmux behavior

components/esp_modem/include/generate/esp_modem_command_declare.inc
This PR is removing duplicated line in docs: description of `esp_modem_at_raw()` (C-API)
=> [modem]: Fix esp_modem_at_raw() description in docs (C-API) 

ci/detect_component_bump
Fixing CI issue https://github.com/espressif/esp-protocols/actions/runs/10898995397/job/30243405603
After merging https://github.com/espressif/esp-protocols/pull/606 since `mosquitto` is not yet being published to component manager (we don't need to deal with changelogs, versions, tags...)
=> [ci]: Fix for components not published

.gitmodules
Fixing CI docs build https://github.com/espressif/esp-protocols/actions/runs/11051203708/job/30700593570
caused by moving `mosq` -> `mosquitto`
=> [mosquitto]: Fix incorrect upstream mosqutto submodule path

components/esp_wifi_remote/.cz.yaml, components/esp_wifi_remote/CHANGELOG.md, components/esp_wifi_remote/idf_component.yml
- Make esp_hosted default RPC library (1b62adbd)
- Add build test for current IDF examples (50c113e4)
- Support for IDF v5.3 in a separate directory (bde97203)
- Support for IDF v5.4 via a separate dir (e9ac41e1)
- Add slave selection and peview targets (345c4577)
- Fix CMake to use inherent IDF build vars (c454ec09)
- Update per v5.4 espressif/esp-idf@97e42349 (ff5dac70)
- Fix CI builds to generate configs per slave selection (8795d164)
- Depend on esp_hosted only on targets with no WiFi (7ca5ed1d)
- Update per espressif/esp-idf@27f61966 (2e53b81f)
- Fix checking API compat against reference dir (1a57a878)
=> [wifi_remote]: Bump 0.3.0 -> 0.4.0

components/mosquitto/idf_component.yml
followup on the https://github.com/espressif/esp-protocols/pull/610
* the PR didn't produce any `idf_component.yml` changes and thus publishing was skipped
* incorrect link to the development repo
=> [mosquitto]: Fix incorrect link to the component url

components/mdns/mdns.c
With v1.3.0 the mDNS component supports continuous browsing for services by calling `mdns_browse_new()`. In v1.4.0 whenever one wants to stop browsing for a specific service via `mdns_browse_delete()` there is a deadlock resulting in underlying mdns task to block forever, caused by the API locking introduced with the "Fix API race" commits for v1.4.0.
Background:
API requests are generally serialized into the mdns task - this also applies to the ` mdns_browse_...` calls. The request to stop browsing for a service is put into the mdns task queue and is actually handled by the task via `_mdns_execute_action()` -> `_mdns_browse_finish()`. There it performs a linear search through the queue of pending browse requests to find a matching mDNS service/protocol tuple. Upon match it deletes the …
=> [mdns]: Prevent deadlock when deleting a browse request (IDFGH-13947)

components/mdns/mdns.c
When an interface changes from not ready to ready, a PTR query should be sent for all mdns browse on that interface.
=> [mdns]: send PTR query for mdns browse when interface is ready (IDFGH-13841)

components/esp_websocket_client/esp_websocket_client.c
=> Fix race condition when client set to not reconnect

components/esp_websocket_client/esp_websocket_client.c
Switch WebSocket client to use vSemaphoreDelete() to delete its mutex.
No testing was done.
=> fix(websocket): use proper interface to delete semaphore

components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/idf_component.yml
When WiFi disconnects, `esp_websocket_client_task` continues polling
`esp_transport_poll_read()` with a default 1-second timeout.
If a timeout triggers `esp_websocket_client_abort_connection`,
certain resources are released.
However, if `esp_websocket_client_send_with_exact_opcode`
is still blocked at this point, it will cause a crash
when it times out and accesses the released handle.
This fix prevents potential crashes by ensuring proper
synchronization between abort and send functions.
Merges: https://github.com/espressif/esp-protocols/pull/629
---
- add events for begin/end thread ([d7fa24bc](https://github.com/espressif/esp-protocols/commit/d7fa24bc))
- Make example to use certificate bundle ([aecf6f80](https://github.com/espressif/esp-protocols/commit/aecf6f80))
- propagate esp_tls …
=> [websocket]: Prevent crash on network disconnect during send

components/esp_websocket_client/examples/target/main/websocket_example.c
Free allocated buffer in websocket client example application to balance heap-trace.
TODO: in-progress
=> fix(websocket): fix example buffer leak

components/esp_modem/examples/modem_console/main/modem_console_main.cpp, components/esp_modem/include/cxx_include/esp_modem_dce.hpp, components/esp_modem/include/cxx_include/esp_modem_dte.hpp, components/esp_modem/include/cxx_include/esp_modem_types.hpp, components/esp_modem/src/esp_modem_dce.cpp, components/esp_modem/src/esp_modem_dte.cpp, components/esp_modem/src/esp_modem_netif.cpp
* Supports only DATA and PPP mode
=> [modem]: Add support for guessing mode

docs/esp_modem/en/README.rst
* Fixes the link to target tests in the docs
* Closes https://github.com/espressif/esp-protocols/issues/664
=> [modem]: Fix docs to link tests correctly

components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml, docs/esp_modem/en/README.rst
* Minor documentation update (closes https://github.com/espressif/esp-protocols/issues/507)
* Bump to v1.2.0 
---
- Add support for guessing mode ([52598e5f](https://github.com/espressif/esp-protocols/commit/52598e5f))
- Delete CMUX internal implementation even if terminal exit fails ([0e0cbd6b](https://github.com/espressif/esp-protocols/commit/0e0cbd6b))
- Add support for handling URC ([1b6a3b3b](https://github.com/espressif/esp-protocols/commit/1b6a3b3b), [#180](https://github.com/espressif/esp-protocols/issues/180))
- add ability to change ESP_MODEM_C_API_STR_MAX from Kconfig ([17909892](https://github.com/espressif/esp-protocols/commit/17909892))
- Added target test config with CHAP authentication ([f8ae7def](https://github.com/espressif/esp-protocols/commit/f8ae7def))
- example add …
=> [modem]: bump: 1.1.0 -> 1.2.0

components/mdns/include/mdns.h, components/mdns/mdns.c
Currently, the subtype related API has only one for adding a subtype on some services. This PR introduces new APIs to add/remove/update the subtypes in the mdns service. Also current logic will send nothing on the netif when there is a new subtype added, this PR announces the multicast query response on each netif when a new or a series of subtypes are added.
* Introduce new APIs to add/remove/update the subtypes in the mdns service.
* Send the announce packets when subtypes are the first time to be added on the mdns.
* Updated and removed the subtype, then browsed a query using `avahi`, checked the PTR answer using wireshark.
* Added multiple subtypes and then checked the announce packets via wireshark, all subtypes are included in the response packets.
=> feat(mdns): support update subtype (IDFGH-14068)

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
* Publishes recent changes from https://github.com/espressif/esp-protocols/pull/693
* Addresses component manager warnings from https://github.com/espressif/esp-protocols/actions/runs/11834499548/job/32975304348
---
- support update subtype ([062b8dca](https://github.com/espressif/esp-protocols/commit/062b8dca))
- chore(mdns): Add more info to idf_component.yml ([4a1cb65c](https://github.com/espressif/esp-protocols/commit/4a1cb65c))
=> [mdns]: Bump to v1.4.2

.github/workflows/modem__build-host-tests.yml, components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/examples/ap_to_pppos/README.md, components/esp_modem/examples/linux_modem/README.md, components/esp_modem/examples/modem_console/README.md, components/esp_modem/examples/modem_console/main/Kconfig.projbuild, components/esp_modem/examples/modem_psm/main/Kconfig.projbuild, components/esp_modem/examples/modem_tcp_client/README.md, components/esp_modem/examples/modem_tcp_client/main/Kconfig.projbuild, components/esp_modem/examples/pppos_client/README.md, components/esp_modem/examples/pppos_client/main/Kconfig.projbuild, components/esp_modem/examples/simple_cmux_client/README.md, components/esp_modem/examples/simple_cmux_client/main/Kconfig.projbuild, components/esp_modem/idf_component.yml, components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/include/esp_private/c_api_wrapper.hpp, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/src/esp_modem_uart.cpp, components/esp_modem/test/target/main/Kconfig.projbuild
`+` some other minor fixes
* followup from https://github.com/espressif/esp-protocols/pull/620 -- Adding C-API
* fixes https://github.com/espressif/esp-protocols/issues/667
* fixes https://github.com/espressif/esp-protocols/issues/558
* removes v4.4 IDF release (from tests and references)
* adds v5.4 IDF into CI checks
---
Release as:
- Use higher GPIO range to support new chips ([428fdbbd](https://github.com/espressif/esp-protocols/commit/428fdbbd), [#558](https://github.com/espressif/esp-protocols/issues/558))
- Remove tests and support for IDFv4.4, added IDFv5.4 ([433a033f](https://github.com/espressif/esp-protocols/commit/433a033f))
- Fix typo GENETIC -> GENERIC in mode types ([090b1ff8](https://github.com/espressif/esp-protocols/commit/090b1ff8), …
=> [modem]: Support for URC handler in C-API -> v1.2.1

.github/workflows/modem__target-test.yml, components/esp_modem/src/esp_modem_cmux.cpp, components/esp_modem/test/target/pytest_pppd.py
=> [modem]: CMUX: ignore URC before entering CMUX

components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml
- Add mode detection to the example ([18f196fa](https://github.com/espressif/esp-protocols/commit/18f196fa))
- Support for pausing network in C-API ([1db83cd1](https://github.com/espressif/esp-protocols/commit/1db83cd1))
- Add support for pausing netif ([247f1681](https://github.com/espressif/esp-protocols/commit/247f1681), [#699](https://github.com/espressif/esp-protocols/issues/699))
- Minor cleanup of pppos example ([5e929902](https://github.com/espressif/esp-protocols/commit/5e929902))
- Fix PPP mode detection to accept LCP/conf ([c989c6ad](https://github.com/espressif/esp-protocols/commit/c989c6ad))
- Refine mode switch data->command ([8b6ea331](https://github.com/espressif/esp-protocols/commit/8b6ea331), [#692](https://github.com/espressif/esp-protocols/issues/692))
- Detect serial …
=> [modem]: bump 1.2.1 -> 1.3.0

components/esp_websocket_client/esp_websocket_client.c
Remove an unused structure member and realign another. This makes the code easier to work on when working with reconnection.
WebSocket client was compiled and connected to server many times.
=> Chore(websocket) tidy up two small issues

components/sock_utils/.cz.yaml, components/sock_utils/CHANGELOG.md, components/sock_utils/CMakeLists.txt, components/sock_utils/README.md, components/sock_utils/idf_component.yml, components/sock_utils/include/netdb_macros.h
- Declare socketpar and gai-error via standard headers ([7f103572](https://github.com/espressif/esp-protocols/commit/7f103572))
- Add support for gethostname() ([f7c0b756](https://github.com/espressif/esp-protocols/commit/f7c0b756))
=> [sock-utils]: Bump 0.1 -> 0.2

components/sock_utils/.cz.yaml, components/sock_utils/CHANGELOG.md, components/sock_utils/idf_component.yml, components/sock_utils/include/netdb_macros.h
Some macros could be defined already in standard  headers (depending on IDF and compiler version).
Need to pre-include the official headers (since the macros are defined unconditionally).
=> [sock-utils] Fix potential macro conflict

components/mdns/include/mdns.h, components/mdns/mdns.c
Support zero number of subtype item when updating service. Zero number means remove all subtypes registered.
=> feat(mdns): support zero item when update subtype (IDFGH-14369)

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
- support zero item when update subtype ([5bd82c01](https://github.com/espressif/esp-protocols/commit/5bd82c01))
=> [mdns]: bump: 1.4.2 -> 1.4.3

components/mdns/include/mdns.h, components/mdns/mdns.c, components/mdns/mdns_networking_lwip.c, components/mdns/private_include/mdns_private.h, components/mdns/tests/test_afl_fuzz_host/esp32_mock.c
* 9270a1ae fix(mdns): Move MDNS_NAME_BUF_LEN to public headers
* 77532f98 fix(mdns): Cleanup includes in mdns.c
* 5eddc9c8 fix(mdns): Allow advertizing service with port==0
* 980f3d36 fix(mdns): Fixed complier warning if MDNS_MAX_SERVICES==0
* a69123de fix(mdns): Fixed potential out-of-bound interface error
* 80a7b1fd fix(mdns): Fixed incorrect error conversion
* 411dee47 fix(mdns): Fixed potential overflow when allocating txt data
=> [mdns]: Fixed some minor bugs

components/mdns/mdns.c
* https://github.com/espressif/esp-protocols/security/code-scanning/45
* https://github.com/espressif/esp-protocols/security/code-scanning/111
* https://github.com/espressif/esp-protocols/security/code-scanning/108
* https://github.com/espressif/esp-protocols/security/code-scanning/75
* https://github.com/espressif/esp-protocols/security/code-scanning/66
* https://github.com/espressif/esp-protocols/security/code-scanning/61
* https://github.com/espressif/esp-protocols/security/code-scanning/60
* https://github.com/espressif/esp-protocols/security/code-scanning/58
=> [mdns]: Fixes clang-tidy warnings

.github/workflows/mosq__build.yml, docs/requirements.txt
`+` one minor fix in mosqutto CI
---
Job passed in https://github.com/david-cermak/esp-protocols/actions/runs/12867211883/job/35871360425
=> [common]: Fix esp-docs dependencies

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
- supported removal of subtype when updating service ([4ad88e29](https://github.com/espressif/esp-protocols/commit/4ad88e29))
- Fix zero-sized VLA clang-tidy warnings ([196198ec](https://github.com/espressif/esp-protocols/commit/196198ec))
- Remove dead store to arg variable shared ([e838bf03](https://github.com/espressif/esp-protocols/commit/e838bf03))
- Fix name mangling not to use strcpy() ([99b54ac3](https://github.com/espressif/esp-protocols/commit/99b54ac3))
- Fix potential null derefernce in _mdns_execute_action() ([f5be2f41](https://github.com/espressif/esp-protocols/commit/f5be2f41))
- Fix AFL test mock per espressif/esp-idf@a5bc08fb55c ([3d8835cf](https://github.com/espressif/esp-protocols/commit/3d8835cf))
- Fixed potential out-of-bound interface error …
=> [mdns]: Bump 1.4.3 -> 1.5.0

.github/workflows/mosq__build.yml, components/mosquitto/README.md, components/mosquitto/test/README.md, components/mosquitto/test/replace_decorators.py
* To add some tests to mosquitto CI
* To prevent issues with IDF CI
* newly introduced mosquitto [2.0.20] consumes a tiny bit more stack, causing the MQTT stress to fail
=> [mosq]: Add IDF MQTT stress tests to mosquitto CI

components/mdns/mdns.c
When parsing an mDNS packet, for `mDNS browse`:
1. If `_mdns_sync_browse_action(ACTION_BROWSE_SYNC, out_sync_browse)` is called, the memory allocated for the browse will be freed by `_mdns_sync_browse_result_link_free` after processing `ACTION_BROWSE_SYNC` in `_mdns_execute_action`. Therefore, the memory should not be freed prematurely at the end of mDNS packet parsing.
2. If `_mdns_sync_browse_action` is not called but free the `out_sync_browse`, it should not be freed again at the end of mDNS packet parsing.
=> [mdns]: fix incorrect memory free for mdns browse

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml
- Fix incorrect memory free for mdns browse ([4451a8c5](https://github.com/espressif/esp-protocols/commit/4451a8c5))
=> [mdns]: Bump 1.5.0 -> 1.5.1

components/asio/idf_component.yml
This publishes ASIO-1.32-0~0
Related to the bump-commit: ac6a388cdd7f31e113faa9cf132b8c57f1ff4df4 but missed to update idf_component.yml
Used commitizen automation, which refused to update `idf_component.yml` due to invalid sem-ver (`~0` suffix)
=> bump(asio): Publish 1.32.0 to component manager

components/esp_websocket_client/esp_websocket_client.c
This fixes an regression from https://github.com/espressif/esp-protocols/commit/0d8f2a6d53b306803932e9c98522c81898aa9b6b that caused the `error_type` not to be available in the event dispatcher when auto disconnect is disabled.
The `error_type` must be set for the event dispatcher to propagate the right errors in the next event. This is unrelated to whether auto disconnect is enabled or not.
Fixes regression https://github.com/espressif/esp-protocols/pull/626
References https://github.com/espressif/esp-protocols/pull/630
Test steps:
1. Start TLS server on a host machine with an untrusted certificate (e.g. self-signed, wrong name)
2. Let an ESP32 application connect with `esp_websocket_client`
3. Observe the error fields in the disconnected event. They were not propagated. They are now. …
=> fix(websocket): propagate error type (IDFGH-14518)

components/mdns/mdns.c
Move "mdns_name_t name" declaration inside loop to move it out of scope and reclain stack space before recursion call.
Move "mdns_name_t name" declaration inside loop to move it out of scope and reclaim stack space before the recursion call.
Fixes #738 
Tested using patched version on product build. Original was triggering a stack overflow. Stack overflow did not occur with patched version.
=> fix(mdns): Fix _mdns_append_fqdn excessive stack usage (IDFGH-14506)

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml, components/mdns/mdns.c
Closes coverity reported issue: 473829 Dereference null return value
---
- Fix potential NULL deref when sending sub-buy ([e7273c46](https://github.com/espressif/esp-protocols/commit/e7273c46))
- Fix _mdns_append_fqdn excessive stack usage ([bd23c233](https://github.com/espressif/esp-protocols/commit/bd23c233))
=> [mdns]: Bump v1.5.2

components/esp_websocket_client/esp_websocket_client.c
This ensures that the task is awaited on destroy.
This fixes a race condition between two independent actions:
1. The WebSocket task detects a disconnect (e.g. read fails), initiates abort, sets `run` to false, posts the `DISCONNECTED` event, breaks, then posts the `FINISHED` events and deletes the task
2. The application destroys the WebSocket client (e.g. via an asynchronous invocation via receiving the disconnected event)
Currently, in `esp_websocket_client_destroy()` would immediately destroy all resources, because `run` is already `false`. However, the task may still be running, and it needs the resources to cleanly stop the task (e.g. post the `FINISHED` event).
This change ensures that the task has stopped. The task must be stopped before resources can be freed.
The `run` check in …
=> fix(websocket): wait for task on destroy (IDFGH-14533)

components/esp_websocket_client/examples/target/pytest_websocket.py
The test code did accept also connections from clients which didn't present a certificate.
Need to use
```python
ssl_context.verify_mode = ssl.CERT_REQUIRED
```
instead of `verify` in python's SSL context
=> [websocket]: Fix pytest to verify client correctly

components/esp_websocket_client/.cz.yaml, components/esp_websocket_client/CHANGELOG.md, components/esp_websocket_client/idf_component.yml
- Support DS peripheral for mutual TLS ([55385ec3](https://github.com/espressif/esp-protocols/commit/55385ec3))
- wait for task on destroy ([42674b49](https://github.com/espressif/esp-protocols/commit/42674b49))
- Fix pytest to verify client correctly ([9046af8f](https://github.com/espressif/esp-protocols/commit/9046af8f))
- propagate error type ([eeeb9006](https://github.com/espressif/esp-protocols/commit/eeeb9006))
- fix example buffer leak ([5219c39d](https://github.com/espressif/esp-protocols/commit/5219c39d))
- chore(websocket): align structure members ([beb6e57e](https://github.com/espressif/esp-protocols/commit/beb6e57e))
- chore(websocket): remove unused client variable ([15d3a01e](https://github.com/espressif/esp-protocols/commit/15d3a01e))
=> [websocket]:  Bump 1.3.0 -> 1.4.0

.github/workflows/mosq__build.yml
IDF-test was executed even if no `mosq` label added.
---
* with reverted fix and no label: https://github.com/espressif/esp-protocols/actions/runs/13070794874/job/36471822367?pr=753
* after applying the fix (and no lable): The job is skipped: https://github.com/espressif/esp-protocols/actions/runs/13070879813/job/36472073405?pr=753
=> [mosquitto]: Fix minor CI issue

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/examples/target/main/websocket_example.c, components/esp_websocket_client/include/esp_websocket_client.h
- Add event unregister to websocket client
- Minor: Updated code format
=> feat(websocket): add unregister event to websocket client

components/libwebsockets/LICENSE.txt
Libwebsockets and included programs are provided under the terms of the
MIT license shown below, with the exception that some sources are under
a similar permissive license like BSD, or are explicitly CC0 / public
domain to remove any obstacles from basing differently-licensed code on
them.
* Please refer to the LWS LICENSE for more details.
* Espressif port files are licensed under Apache-2.0 license.
* Espressif examples and tests are distributed under Unlicense/CC0.
* https://github.com/espressif/esp-protocols/actions/runs/13414903602/job/37473259829
=> [lws]: Adds missing license info

components/esp_modem/src/esp_modem_dte.cpp
The issue can be reproduced by setting a timeout for waiting for a USB connection (esp_modem_usb_term_config.timeou_ms). When the timeout occurs, the value of `primary_term` becomes null.
If either primary_term or secondary_term is `nullptr`, the set_command_callbacks function attempts to access invalid values. For example, in the first line of the function, `primary_term->set_read_cb([this](uint8_t *data, size_t len)`, the program tries to dereference primary_term, leading to a `LoadProhibited` exception and crashing the application.
To address this, I added a validation check in the DTE constructor to ensure the values are valid. Additionally, I handled the exception in the standard exception handler.
I test the changes in a ESP32S3.
---
Before submitting a Pull Request, please ensure …
=> fix(modem): handle nullptr in DTE constructors to prevent invalid access (IDFGH-14688)

.github/workflows/clang-tidy.yml, components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/CMakeLists.txt, components/mdns/examples/query_advertise/main/mdns_example_main.c, components/mdns/idf_component.yml, components/mdns/include/mdns.h, components/mdns/tests/host_test/components/esp_netif_linux/esp_netif_linux.c, components/mdns/tests/host_test/main/main.c, components/mdns/tests/test_afl_fuzz_host/test.c, components/mdns/tests/test_apps/main/main.c, components/mdns/tests/unit_test/main/test_mdns.c
* Brings up https://github.com/espressif/esp-protocols/pull/772
---
- Add version keys ([e01e67e7](https://github.com/espressif/esp-protocols/commit/e01e67e7))
- Reformat mdns sources per indent-cont=120 ([c7663cde](https://github.com/espressif/esp-protocols/commit/c7663cde))
=> [mdns]: Bump 1.7.0 -> 1.8.0

components/mosquitto/.cz.yaml, components/mosquitto/CHANGELOG.md, components/mosquitto/CMakeLists.txt, components/mosquitto/Kconfig, components/mosquitto/idf_component.yml, components/mosquitto/port/config.c, components/mosquitto/port/mosq_time.c, components/mosquitto/port/priv_include/config.h
- Allow user to enable $SYS/# topics
- Provide a port layer for mosquitto get time functions. 
Run the example with the new Kconfig options enabled.
---
=> Add config to enable SYS on mosquito and bump version

.github/workflows/mosq__build.yml
* Per changes in https://github.com/espressif/esp-idf/commit/daf2d31008446592c66479e11484d79b94ef1d92
=> [mosq]: Fix pytest to use latest embedded packages

components/mdns/.cz.yaml, components/mdns/CHANGELOG.md, components/mdns/idf_component.yml, components/mdns/mdns.c
Issue discovered when fuzzing packet parser,
received packet with inconsistent txt section caused issues on final cleanup
=> [mdns]: Fix parsing incorrect txt records

.pre-commit-config.yaml, components/esp_modem/include/cxx17_include/esp_modem_command_library_17.hpp, components/esp_modem/include/cxx_include/esp_modem_api.hpp, components/esp_modem/include/cxx_include/esp_modem_dce_factory.hpp, components/esp_modem/include/cxx_include/esp_modem_dce_module.hpp, components/esp_modem/include/esp_modem_c_api_types.h, components/esp_modem/include/esp_private/c_api_wrapper.hpp, components/esp_modem/include/generate/esp_modem_command_declare.inc, components/esp_modem/src/esp_modem_api.cpp, components/esp_modem/src/esp_modem_c_api.cpp, components/esp_modem/src/esp_modem_command_library.cpp, components/esp_modem/src/esp_modem_modules.cpp
This pull-request adds support for the Sequans GM02S(P) modem. The implementation was tested on the DPTechnics Walter board (ESP32-S3 + GM02SP). Also included in this pull-request is support for low power modes using eDRX and PSM
---
1) Added SQNGM02S modem module.
2) Added connect function for SQNGM02S modem.
3) changed set_data_mode() function: as it should not call the set pdp_context function as the GM02S modem has to have the PDP context already set to register/connect with the network.
> [!NOTE]
> The connect function might be generalised for modems that need to be registered with the network before doing other AT-commands
1) added function to config the registration urc: `config_network_registration_urc`.
2) added function to get the current registration state: …
=> feat(module): add support for sequans GM02S modem (DPTechnics) (IDFGH-14891)

components/esp_modem/.cz.yaml, components/esp_modem/CHANGELOG.md, components/esp_modem/idf_component.yml
- added config_edrx api function ([74b7d85d](https://github.com/espressif/esp-protocols/commit/74b7d85d))
- added sqn_gm02s connect function ([b97dfc08](https://github.com/espressif/esp-protocols/commit/b97dfc08))
- add support for sequans GM02S modem ([8560f021](https://github.com/espressif/esp-protocols/commit/8560f021))
- Fix cmux log message ([6ed672da](https://github.com/espressif/esp-protocols/commit/6ed672da))
- fixed minor code mistakes. ([317faf89](https://github.com/espressif/esp-protocols/commit/317faf89))
- handle nullptr in DTE constructors to prevent invalid access ([95b56600](https://github.com/espressif/esp-protocols/commit/95b56600))
=> [modem]: Bump 1.3.0 -> 1.4.0

examples/esp_netif/multiple_netifs/README.md, examples/esp_netif/multiple_netifs/main/Kconfig.projbuild, examples/esp_netif/multiple_netifs/main/ethernet_connect.c, examples/esp_netif/multiple_netifs/main/multi_netif_main.c, examples/esp_netif/multiple_netifs/main/ppp_connect.c, examples/esp_netif/multiple_netifs/main/wifi_connect.c, examples/esp_netif/multiple_netifs/sdkconfig.defaults
Latest IDF supports `CONFIG_ESP_NETIF_SET_DNS_PER_DEFAULT_NETIF` config option which restores global DNS server information from "per-netif" records whenever a new netif is selected for routing (set as default).
=> [examples]: Make multi-netif example working with DNS_PER_DEFAULT_NETIF

components/esp_websocket_client/esp_websocket_client.c
Prevent deadlocks when reserving locks in WEBSOCKET_EVENT_DATA handler, and lock is held by another thread sending a websocket message.
Fix high latency caused by writers serialized with WEBSOCKET_EVENT_DATA while calling esp_websocket_client_send(), even when TCP window has enough space for the entire message being queued to send.
Multiple writers are still serialized at fragment boundaries, but only with other writers and websocket error updates.
Fixes #625.
I tested with a WebSocket echo server running on the same WiFi access point, using the target-example with the following modifications:
* AppMain thread tries to send 20 unfragmented frames, waiting 100ms between frames.
* WebSocket client is patched to record the time taken to send each frame.
* WEBSOCKET_EVENT_DATA handler calls …
=> fix(websocket): release client-lock during WEBSOCKET_EVENT_DATA (IDFGH-14545)

.github/workflows/clang-tidy.yml
Address some of the code-scanning issues reported in https://github.com/espressif/esp-protocols/security/code-scanning
=> [lws]: Fix many file-not-found errors on clang-tidy job

test_app/CMakeLists.txt
Since lws hardcodes some flags in CMakeLists.txt, which causes compilation issues with:
* mbedtls, 
* generated lws_config.h
* flags `-mlongcalls`
see: https://github.com/warmcat/libwebsockets/blob/a74362ffdd17b7f6293f675edef6d602096a1e29/CMakeLists.txt#L898
=> fix(lws): Remove clang tidy checks

.github/workflows/eppp__build.yml, components/eppp_link/.cz.yaml, components/eppp_link/CHANGELOG.md, components/eppp_link/CMakeLists.txt, components/eppp_link/Kconfig, components/eppp_link/README.md, components/eppp_link/eppp_eth.c, components/eppp_link/eppp_link.c, components/eppp_link/eppp_netif_tun.c, components/eppp_link/eppp_sdio.c, components/eppp_link/eppp_sdio_slave.c, components/eppp_link/eppp_spi.c, components/eppp_link/eppp_transport.h, components/eppp_link/eppp_uart.c, components/eppp_link/examples/host/main/Kconfig.projbuild, components/eppp_link/examples/host/main/app_main.c, components/eppp_link/examples/slave/main/Kconfig.projbuild, components/eppp_link/examples/slave/main/eppp_slave.c, components/eppp_link/idf_component.yml, components/eppp_link/include/eppp_link.h, components/eppp_link/include/eppp_transport_eth.h, components/eppp_link/include/eppp_transport_sdio.h, components/eppp_link/include/eppp_transport_spi.h, components/eppp_link/include/eppp_transport_uart.h
=> feat(eppp): Add support for TUN interface

components/eppp_link/.cz.yaml, components/eppp_link/CHANGELOG.md, components/eppp_link/eppp_link.c, components/eppp_link/idf_component.yml
Fix build issue: https://github.com/espressif/esp-wifi-remote/actions/runs/15608335998/job/43963036566 since PPP is OFF by default in lwip
=> [eppp]: Fix NETIF_PPP_STATUS link issue if PPP disabled in lwip

.github/workflows/mdns__host-tests.yml
Fixes: https://github.com/espressif/esp-protocols/actions/runs/15610323341/job/43969460962
`idf-build-apps` >= v2.11 won't build preview targets
In the followup PR: Fix it in our wrapper https://github.com/espressif/esp-protocols/blob/master/ci/build_apps.py
=> [mdns]: Fix host tests by freezing idf-build-apps to 2.10

components/esp_modem/src/esp_modem_dce.cpp, components/esp_modem/src/esp_modem_dte.cpp
Closes https://github.com/espressif/esp-protocols/issues/801
=> [modem]: Fix autodetect to support ACFC mode in PPP frames

components/esp_dns/esp_dns_doh.c
Fixes https://github.com/espressif/esp-protocols/actions/runs/15843752057/job/44661192291
http-client API added `HTTP_EVENT_ON_HEADERS_COMPLETE` on the latest IDF master
=> [dns]: Fix http event handler to accept default case

components/esp_modem/src/esp_modem_dte.cpp
Currently the urc_line handler function does not consume the buffer, this PR aims to fix this.
The PR uses the implementation discussed here: https://github.com/espressif/esp-protocols/pull/810
All changes where tested useing the DPTechnics walter board using sequans GM02S IoT modem
---
=> fix(modem): Consume buffer after handled URC

components/esp_websocket_client/esp_websocket_client.c, components/esp_websocket_client/include/esp_websocket_client.h
Add a flag to client configuration to enable reconnection after websocket closed cleanly. Needed to support protocols like Socket.IO, where some websocket closes issued by the server are reconnectable.
Testing consists of issuing a websocket close from the server, and the client reconnecting.
=> feat(websocket): add ability to reconnect after close (IDFGH-15455)

components/eppp_link/.cz.yaml, components/eppp_link/CHANGELOG.md, components/eppp_link/Kconfig, components/eppp_link/README.md, components/eppp_link/detailed_description.md, components/eppp_link/eppp_link.c, components/eppp_link/eppp_sdio.c, components/eppp_link/eppp_sdio.h, components/eppp_link/eppp_sdio_host.c, components/eppp_link/eppp_sdio_slave.c, components/eppp_link/eppp_spi.c, components/eppp_link/eppp_transport.h, components/eppp_link/eppp_uart.c, components/eppp_link/examples/host/main/CMakeLists.txt, components/eppp_link/examples/host/main/Kconfig.projbuild, components/eppp_link/examples/host/main/app_main.c, components/eppp_link/examples/host/main/channel_wifi_station.c, components/eppp_link/examples/host/main/idf_component.yml, components/eppp_link/examples/slave/main/CMakeLists.txt, components/eppp_link/examples/slave/main/Kconfig.projbuild, components/eppp_link/examples/slave/main/channel_wifi_station.c, components/eppp_link/examples/slave/main/eppp_slave.c, components/eppp_link/idf_component.yml, components/eppp_link/include/eppp_link.h
* Adds support for custom channels
* Could be used to transmit/receive any data
* Demonstrated with channeling WiFi 802.11 frames from host to slave (+ one chat channel)
=> [eppp-link]: Support for channels

examples/mqtt/main/Kconfig.projbuild
Again `mqtt.eclipseprojects.io` ->  `mqtt://test.mosquitto.org`
Fixes: https://github.com/espressif/esp-protocols/actions/runs/16224632056/job/45813522813
=> [examples]: Use another public broker for MQTT example

components/esp_modem/Kconfig, components/esp_modem/include/cxx_include/esp_modem_dce_factory.hpp, components/esp_modem/src/esp_modem_netif.cpp
* Closes https://github.com/espressif/esp-protocols/issues/851
Supports building (and using) modem library without PPP mode.
It is already possible (see the [tcp-client](https://github.com/espressif/esp-protocols/tree/master/components/esp_modem/examples/modem_tcp_client) examples), but it only works with C++ interface.
This is more straight-forward approach.
It also assures PPP mode is "selected" for new projects that pull `esp_modem` component.
=> [modem]: Support esp-modem use without PPP

components/eppp_link/eppp_netif_tun.c, components/eppp_link/eppp_spi.c, components/eppp_link/eppp_uart.c, components/eppp_link/include/eppp_link.h
Closes https://github.com/espressif/esp-protocols/issues/868
Closes https://github.com/espressif/esp-protocols/issues/867
Closes https://github.com/espressif/esp-protocols/issues/870
=> [eppp]: Minor fixes v1.0

components/mosquitto/CMakeLists.txt, components/mosquitto/examples/broker/main/CMakeLists.txt
`newlib` component is going to be renamed to `esp_libc`
I don't see reasons for adding the component via PRIV_REQUIRES because it is already in g1_components
If you lack some private `newlib` headers, I believe they should be made public.
- ESP-IDF MR !41584
---
=> fix: drop newlib from PRIV_REQUIRES

components/eppp_link/.cz.yaml, components/eppp_link/CHANGELOG.md, components/eppp_link/idf_component.yml
- Add support for UART flow control ([cd57f1bb](https://github.com/espressif/esp-protocols/commit/cd57f1bb), [#870](https://github.com/espressif/esp-protocols/issues/870))
- Fix SPI transport to allow already init GPIO ISR ([497ee2d6](https://github.com/espressif/esp-protocols/commit/497ee2d6), [#868](https://github.com/espressif/esp-protocols/issues/868))
- Fix stack-overflow in ping task for TUN netif ([b2568a3d](https://github.com/espressif/esp-protocols/commit/b2568a3d), [#867](https://github.com/espressif/esp-protocols/issues/867))
=> [eppp]: Bump 1.0.1 -> 1.1.0

components/esp_websocket_client/esp_websocket_client.c
- Handle the HTTP 3xx status family and redirect the connection to the new host.
=> feat(websocket): Add websocket HTTP redirect
